// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chatrooms.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	FromPeerID string `protobuf:"bytes,1,opt,name=fromPeerID,proto3" json:"fromPeerID,omitempty"`
	// Types that are valid to be assigned to Message:
	//	*Message_ChatMessage
	//	*Message_TypingMessage
	Message              isMessage_Message `protobuf_oneof:"message"`
	Signature            []byte            `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_779e98f1dc972d96, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetFromPeerID() string {
	if m != nil {
		return m.FromPeerID
	}
	return ""
}

type isMessage_Message interface {
	isMessage_Message()
}

type Message_ChatMessage struct {
	ChatMessage *Message_Chat `protobuf:"bytes,2,opt,name=chatMessage,proto3,oneof"`
}

type Message_TypingMessage struct {
	TypingMessage *Message_Typing `protobuf:"bytes,3,opt,name=typingMessage,proto3,oneof"`
}

func (*Message_ChatMessage) isMessage_Message() {}

func (*Message_TypingMessage) isMessage_Message() {}

func (m *Message) GetMessage() isMessage_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *Message) GetChatMessage() *Message_Chat {
	if x, ok := m.GetMessage().(*Message_ChatMessage); ok {
		return x.ChatMessage
	}
	return nil
}

func (m *Message) GetTypingMessage() *Message_Typing {
	if x, ok := m.GetMessage().(*Message_TypingMessage); ok {
		return x.TypingMessage
	}
	return nil
}

func (m *Message) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Message) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Message_ChatMessage)(nil),
		(*Message_TypingMessage)(nil),
	}
}

type Message_Chat struct {
	Message              string               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Link                 string               `protobuf:"bytes,2,opt,name=link,proto3" json:"link,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	PreviousCIDs         []string             `protobuf:"bytes,4,rep,name=previousCIDs,proto3" json:"previousCIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Message_Chat) Reset()         { *m = Message_Chat{} }
func (m *Message_Chat) String() string { return proto.CompactTextString(m) }
func (*Message_Chat) ProtoMessage()    {}
func (*Message_Chat) Descriptor() ([]byte, []int) {
	return fileDescriptor_779e98f1dc972d96, []int{0, 0}
}

func (m *Message_Chat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message_Chat.Unmarshal(m, b)
}
func (m *Message_Chat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message_Chat.Marshal(b, m, deterministic)
}
func (m *Message_Chat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message_Chat.Merge(m, src)
}
func (m *Message_Chat) XXX_Size() int {
	return xxx_messageInfo_Message_Chat.Size(m)
}
func (m *Message_Chat) XXX_DiscardUnknown() {
	xxx_messageInfo_Message_Chat.DiscardUnknown(m)
}

var xxx_messageInfo_Message_Chat proto.InternalMessageInfo

func (m *Message_Chat) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Message_Chat) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

func (m *Message_Chat) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Message_Chat) GetPreviousCIDs() []string {
	if m != nil {
		return m.PreviousCIDs
	}
	return nil
}

type Message_Typing struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message_Typing) Reset()         { *m = Message_Typing{} }
func (m *Message_Typing) String() string { return proto.CompactTextString(m) }
func (*Message_Typing) ProtoMessage()    {}
func (*Message_Typing) Descriptor() ([]byte, []int) {
	return fileDescriptor_779e98f1dc972d96, []int{0, 1}
}

func (m *Message_Typing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message_Typing.Unmarshal(m, b)
}
func (m *Message_Typing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message_Typing.Marshal(b, m, deterministic)
}
func (m *Message_Typing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message_Typing.Merge(m, src)
}
func (m *Message_Typing) XXX_Size() int {
	return xxx_messageInfo_Message_Typing.Size(m)
}
func (m *Message_Typing) XXX_DiscardUnknown() {
	xxx_messageInfo_Message_Typing.DiscardUnknown(m)
}

var xxx_messageInfo_Message_Typing proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Message)(nil), "Message")
	proto.RegisterType((*Message_Chat)(nil), "Message.Chat")
	proto.RegisterType((*Message_Typing)(nil), "Message.Typing")
}

func init() { proto.RegisterFile("chatrooms.proto", fileDescriptor_779e98f1dc972d96) }

var fileDescriptor_779e98f1dc972d96 = []byte{
	// 276 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xbf, 0x6e, 0xf2, 0x30,
	0x14, 0xc5, 0x49, 0x88, 0xe0, 0xf3, 0x05, 0x84, 0xe4, 0x29, 0x8a, 0x3e, 0xb5, 0x11, 0x53, 0x26,
	0xa3, 0xb6, 0x43, 0x3b, 0x03, 0x03, 0x0c, 0x95, 0x2a, 0x8b, 0xa9, 0x9b, 0x53, 0x19, 0x63, 0x15,
	0xc7, 0x96, 0xed, 0x54, 0xea, 0x6b, 0xf4, 0xfd, 0xfa, 0x2e, 0x15, 0xce, 0x1f, 0x60, 0xcb, 0x3d,
	0xf9, 0x9d, 0xe3, 0x73, 0x2f, 0xcc, 0x3f, 0x8e, 0xcc, 0x5b, 0xad, 0x95, 0x23, 0xc6, 0x6a, 0xaf,
	0xb3, 0x7b, 0xa1, 0xb5, 0x38, 0xf1, 0x65, 0x98, 0xca, 0xfa, 0xb0, 0xf4, 0x52, 0x71, 0xe7, 0x99,
	0x32, 0x0d, 0xb0, 0xf8, 0x8d, 0x61, 0xfc, 0xca, 0x9d, 0x63, 0x82, 0xe3, 0x3b, 0x80, 0x83, 0xd5,
	0xea, 0x8d, 0x73, 0xbb, 0xdb, 0xa4, 0x51, 0x1e, 0x15, 0x88, 0x5e, 0x29, 0xf8, 0x01, 0x26, 0xe7,
	0xfc, 0x16, 0x4f, 0xe3, 0x3c, 0x2a, 0x26, 0x8f, 0x33, 0xd2, 0xce, 0x64, 0x7d, 0x64, 0x7e, 0x3b,
	0xa0, 0xd7, 0x0c, 0x7e, 0x86, 0x99, 0xff, 0x36, 0xb2, 0x12, 0x9d, 0x69, 0x18, 0x4c, 0xf3, 0xde,
	0xb4, 0x0f, 0x7f, 0xb7, 0x03, 0x7a, 0xcb, 0xe1, 0xff, 0x80, 0x9c, 0x14, 0x15, 0xf3, 0xb5, 0xe5,
	0x69, 0x92, 0x47, 0xc5, 0x94, 0x5e, 0x84, 0xec, 0x27, 0x82, 0xe4, 0xfc, 0x1c, 0x4e, 0x61, 0xac,
	0xda, 0xe4, 0xa6, 0x6f, 0x37, 0x62, 0x0c, 0xc9, 0x49, 0x56, 0x9f, 0xa1, 0x25, 0xa2, 0xe1, 0x1b,
	0xbf, 0x00, 0xea, 0xf7, 0x6f, 0x9b, 0x64, 0xa4, 0xb9, 0x10, 0xe9, 0x2e, 0x44, 0xf6, 0x1d, 0x41,
	0x2f, 0x30, 0x5e, 0xc0, 0xd4, 0x58, 0xfe, 0x25, 0x75, 0xed, 0xd6, 0xbb, 0x8d, 0x4b, 0x93, 0x7c,
	0x58, 0x20, 0x7a, 0xa3, 0x65, 0xff, 0x60, 0xd4, 0x6c, 0xb3, 0x42, 0x7d, 0xab, 0x55, 0xf2, 0x1e,
	0x9b, 0xb2, 0x1c, 0x85, 0xf4, 0xa7, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xea, 0x79, 0xa8, 0xcb,
	0xa0, 0x01, 0x00, 0x00,
}
