// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Currency struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Divisibility         uint32   `protobuf:"varint,2,opt,name=divisibility,proto3" json:"divisibility,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CurrencyType         string   `protobuf:"bytes,4,opt,name=currencyType,proto3" json:"currencyType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Currency) Reset()         { *m = Currency{} }
func (m *Currency) String() string { return proto.CompactTextString(m) }
func (*Currency) ProtoMessage()    {}
func (*Currency) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *Currency) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Currency.Unmarshal(m, b)
}
func (m *Currency) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Currency.Marshal(b, m, deterministic)
}
func (m *Currency) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Currency.Merge(m, src)
}
func (m *Currency) XXX_Size() int {
	return xxx_messageInfo_Currency.Size(m)
}
func (m *Currency) XXX_DiscardUnknown() {
	xxx_messageInfo_Currency.DiscardUnknown(m)
}

var xxx_messageInfo_Currency proto.InternalMessageInfo

func (m *Currency) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Currency) GetDivisibility() uint32 {
	if m != nil {
		return m.Divisibility
	}
	return 0
}

func (m *Currency) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Currency) GetCurrencyType() string {
	if m != nil {
		return m.CurrencyType
	}
	return ""
}

type CurrencyValue struct {
	Currency             *Currency `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	Amount               string    `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CurrencyValue) Reset()         { *m = CurrencyValue{} }
func (m *CurrencyValue) String() string { return proto.CompactTextString(m) }
func (*CurrencyValue) ProtoMessage()    {}
func (*CurrencyValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

func (m *CurrencyValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CurrencyValue.Unmarshal(m, b)
}
func (m *CurrencyValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CurrencyValue.Marshal(b, m, deterministic)
}
func (m *CurrencyValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurrencyValue.Merge(m, src)
}
func (m *CurrencyValue) XXX_Size() int {
	return xxx_messageInfo_CurrencyValue.Size(m)
}
func (m *CurrencyValue) XXX_DiscardUnknown() {
	xxx_messageInfo_CurrencyValue.DiscardUnknown(m)
}

var xxx_messageInfo_CurrencyValue proto.InternalMessageInfo

func (m *CurrencyValue) GetCurrency() *Currency {
	if m != nil {
		return m.Currency
	}
	return nil
}

func (m *CurrencyValue) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

type ID struct {
	PeerID               string      `protobuf:"bytes,1,opt,name=peerID,proto3" json:"peerID,omitempty"`
	Handle               string      `protobuf:"bytes,2,opt,name=handle,proto3" json:"handle,omitempty"`
	Pubkeys              *ID_Pubkeys `protobuf:"bytes,3,opt,name=pubkeys,proto3" json:"pubkeys,omitempty"`
	Sig                  []byte      `protobuf:"bytes,4,opt,name=sig,proto3" json:"sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ID) Reset()         { *m = ID{} }
func (m *ID) String() string { return proto.CompactTextString(m) }
func (*ID) ProtoMessage()    {}
func (*ID) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{2}
}

func (m *ID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ID.Unmarshal(m, b)
}
func (m *ID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ID.Marshal(b, m, deterministic)
}
func (m *ID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ID.Merge(m, src)
}
func (m *ID) XXX_Size() int {
	return xxx_messageInfo_ID.Size(m)
}
func (m *ID) XXX_DiscardUnknown() {
	xxx_messageInfo_ID.DiscardUnknown(m)
}

var xxx_messageInfo_ID proto.InternalMessageInfo

func (m *ID) GetPeerID() string {
	if m != nil {
		return m.PeerID
	}
	return ""
}

func (m *ID) GetHandle() string {
	if m != nil {
		return m.Handle
	}
	return ""
}

func (m *ID) GetPubkeys() *ID_Pubkeys {
	if m != nil {
		return m.Pubkeys
	}
	return nil
}

func (m *ID) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

type ID_Pubkeys struct {
	Identity             []byte   `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Escrow               []byte   `protobuf:"bytes,2,opt,name=escrow,proto3" json:"escrow,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ID_Pubkeys) Reset()         { *m = ID_Pubkeys{} }
func (m *ID_Pubkeys) String() string { return proto.CompactTextString(m) }
func (*ID_Pubkeys) ProtoMessage()    {}
func (*ID_Pubkeys) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{2, 0}
}

func (m *ID_Pubkeys) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ID_Pubkeys.Unmarshal(m, b)
}
func (m *ID_Pubkeys) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ID_Pubkeys.Marshal(b, m, deterministic)
}
func (m *ID_Pubkeys) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ID_Pubkeys.Merge(m, src)
}
func (m *ID_Pubkeys) XXX_Size() int {
	return xxx_messageInfo_ID_Pubkeys.Size(m)
}
func (m *ID_Pubkeys) XXX_DiscardUnknown() {
	xxx_messageInfo_ID_Pubkeys.DiscardUnknown(m)
}

var xxx_messageInfo_ID_Pubkeys proto.InternalMessageInfo

func (m *ID_Pubkeys) GetIdentity() []byte {
	if m != nil {
		return m.Identity
	}
	return nil
}

func (m *ID_Pubkeys) GetEscrow() []byte {
	if m != nil {
		return m.Escrow
	}
	return nil
}

type EscrowSignature struct {
	InputIndex           uint32   `protobuf:"varint,1,opt,name=inputIndex,proto3" json:"inputIndex,omitempty"`
	Sig                  []byte   `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EscrowSignature) Reset()         { *m = EscrowSignature{} }
func (m *EscrowSignature) String() string { return proto.CompactTextString(m) }
func (*EscrowSignature) ProtoMessage()    {}
func (*EscrowSignature) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{3}
}

func (m *EscrowSignature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EscrowSignature.Unmarshal(m, b)
}
func (m *EscrowSignature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EscrowSignature.Marshal(b, m, deterministic)
}
func (m *EscrowSignature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EscrowSignature.Merge(m, src)
}
func (m *EscrowSignature) XXX_Size() int {
	return xxx_messageInfo_EscrowSignature.Size(m)
}
func (m *EscrowSignature) XXX_DiscardUnknown() {
	xxx_messageInfo_EscrowSignature.DiscardUnknown(m)
}

var xxx_messageInfo_EscrowSignature proto.InternalMessageInfo

func (m *EscrowSignature) GetInputIndex() uint32 {
	if m != nil {
		return m.InputIndex
	}
	return 0
}

func (m *EscrowSignature) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

func init() {
	proto.RegisterType((*Currency)(nil), "Currency")
	proto.RegisterType((*CurrencyValue)(nil), "CurrencyValue")
	proto.RegisterType((*ID)(nil), "ID")
	proto.RegisterType((*ID_Pubkeys)(nil), "ID.Pubkeys")
	proto.RegisterType((*EscrowSignature)(nil), "EscrowSignature")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 303 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x51, 0x3d, 0x4f, 0xf3, 0x30,
	0x10, 0x56, 0xd2, 0xaa, 0x1f, 0xd7, 0x54, 0xef, 0x2b, 0x0f, 0x28, 0xea, 0x80, 0xaa, 0x48, 0x95,
	0x3a, 0x65, 0x28, 0x33, 0x0b, 0x2d, 0x43, 0x16, 0x84, 0x0c, 0x62, 0x60, 0xcb, 0xc7, 0xa9, 0x58,
	0x34, 0xb6, 0xe5, 0xd8, 0x40, 0xf8, 0x4d, 0xfc, 0x48, 0x64, 0xd7, 0x8e, 0xe8, 0x76, 0xcf, 0x97,
	0xef, 0xb9, 0x04, 0x92, 0x5a, 0xb4, 0xad, 0xe0, 0xb9, 0x54, 0x42, 0x8b, 0xec, 0x1b, 0x66, 0x7b,
	0xa3, 0x14, 0xf2, 0xba, 0x27, 0x04, 0xc6, 0xb5, 0x68, 0x30, 0x8d, 0xd6, 0xd1, 0x76, 0x4e, 0xdd,
	0x4c, 0x32, 0x48, 0x1a, 0xf6, 0xc1, 0x3a, 0x56, 0xb1, 0x13, 0xd3, 0x7d, 0x1a, 0xaf, 0xa3, 0xed,
	0x92, 0x5e, 0x70, 0x36, 0xc7, 0xcb, 0x16, 0xd3, 0xd1, 0x39, 0x67, 0x67, 0x9b, 0xab, 0xfd, 0xbb,
	0xcf, 0xbd, 0xc4, 0x74, 0xec, 0xb4, 0x0b, 0x2e, 0x7b, 0x80, 0x65, 0xd8, 0xfd, 0x52, 0x9e, 0x0c,
	0x92, 0x0d, 0xcc, 0x82, 0xc1, 0x95, 0x58, 0xec, 0xe6, 0x79, 0x70, 0xd0, 0x41, 0x22, 0x57, 0x30,
	0x29, 0x5b, 0x61, 0xb8, 0x76, 0x6d, 0xe6, 0xd4, 0xa3, 0xec, 0x27, 0x82, 0xb8, 0x38, 0x58, 0x59,
	0x22, 0xaa, 0xe2, 0xe0, 0x0f, 0xf1, 0xc8, 0xf2, 0x6f, 0x25, 0x6f, 0x4e, 0x18, 0x62, 0x67, 0x44,
	0x36, 0x30, 0x95, 0xa6, 0x7a, 0xc7, 0xbe, 0x73, 0x17, 0x2c, 0x76, 0x8b, 0xbc, 0x38, 0xe4, 0x8f,
	0x67, 0x8a, 0x06, 0x8d, 0xfc, 0x87, 0x51, 0xc7, 0x8e, 0xee, 0x90, 0x84, 0xda, 0x71, 0x75, 0x0b,
	0x53, 0xef, 0x22, 0x2b, 0x98, 0xb1, 0x06, 0xb9, 0xb6, 0x9f, 0x28, 0x72, 0x8e, 0x01, 0xdb, 0xbd,
	0xd8, 0xd5, 0x4a, 0x7c, 0xba, 0xbd, 0x09, 0xf5, 0x28, 0xdb, 0xc3, 0xbf, 0x7b, 0x37, 0x3d, 0xb1,
	0x23, 0x2f, 0xb5, 0x51, 0x48, 0xae, 0x01, 0x18, 0x97, 0x46, 0x17, 0xbc, 0xc1, 0x2f, 0xf7, 0xd0,
	0x92, 0xfe, 0x61, 0x42, 0x87, 0x78, 0xe8, 0x70, 0x37, 0x7e, 0x8d, 0x65, 0x55, 0x4d, 0xdc, 0xcf,
	0xbc, 0xf9, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x26, 0x1f, 0x6b, 0x2f, 0xdc, 0x01, 0x00, 0x00,
}
