// Code generated by protoc-gen-go. DO NOT EDIT.
// source: listing.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Listing_Metadata_ContractType int32

const (
	Listing_Metadata_PHYSICAL_GOOD  Listing_Metadata_ContractType = 0
	Listing_Metadata_DIGITAL_GOOD   Listing_Metadata_ContractType = 1
	Listing_Metadata_SERVICE        Listing_Metadata_ContractType = 2
	Listing_Metadata_CROWD_FUND     Listing_Metadata_ContractType = 3
	Listing_Metadata_CRYPTOCURRENCY Listing_Metadata_ContractType = 4
)

var Listing_Metadata_ContractType_name = map[int32]string{
	0: "PHYSICAL_GOOD",
	1: "DIGITAL_GOOD",
	2: "SERVICE",
	3: "CROWD_FUND",
	4: "CRYPTOCURRENCY",
}

var Listing_Metadata_ContractType_value = map[string]int32{
	"PHYSICAL_GOOD":  0,
	"DIGITAL_GOOD":   1,
	"SERVICE":        2,
	"CROWD_FUND":     3,
	"CRYPTOCURRENCY": 4,
}

func (x Listing_Metadata_ContractType) String() string {
	return proto.EnumName(Listing_Metadata_ContractType_name, int32(x))
}

func (Listing_Metadata_ContractType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_eb6b76026c8ca063, []int{0, 0, 0}
}

type Listing_Metadata_Format int32

const (
	Listing_Metadata_FIXED_PRICE  Listing_Metadata_Format = 0
	Listing_Metadata_MARKET_PRICE Listing_Metadata_Format = 2
)

var Listing_Metadata_Format_name = map[int32]string{
	0: "FIXED_PRICE",
	2: "MARKET_PRICE",
}

var Listing_Metadata_Format_value = map[string]int32{
	"FIXED_PRICE":  0,
	"MARKET_PRICE": 2,
}

func (x Listing_Metadata_Format) String() string {
	return proto.EnumName(Listing_Metadata_Format_name, int32(x))
}

func (Listing_Metadata_Format) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_eb6b76026c8ca063, []int{0, 0, 1}
}

type Listing_ShippingOption_ShippingType int32

const (
	Listing_ShippingOption_LOCAL_PICKUP Listing_ShippingOption_ShippingType = 0
	Listing_ShippingOption_FIXED_PRICE  Listing_ShippingOption_ShippingType = 1
)

var Listing_ShippingOption_ShippingType_name = map[int32]string{
	0: "LOCAL_PICKUP",
	1: "FIXED_PRICE",
}

var Listing_ShippingOption_ShippingType_value = map[string]int32{
	"LOCAL_PICKUP": 0,
	"FIXED_PRICE":  1,
}

func (x Listing_ShippingOption_ShippingType) String() string {
	return proto.EnumName(Listing_ShippingOption_ShippingType_name, int32(x))
}

func (Listing_ShippingOption_ShippingType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_eb6b76026c8ca063, []int{0, 2, 0}
}

type Listing struct {
	Slug                 string                    `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	VendorID             *ID                       `protobuf:"bytes,2,opt,name=vendorID,proto3" json:"vendorID,omitempty"`
	Metadata             *Listing_Metadata         `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Item                 *Listing_Item             `protobuf:"bytes,4,opt,name=item,proto3" json:"item,omitempty"`
	ShippingOptions      []*Listing_ShippingOption `protobuf:"bytes,5,rep,name=shippingOptions,proto3" json:"shippingOptions,omitempty"`
	Taxes                []*Listing_Tax            `protobuf:"bytes,6,rep,name=taxes,proto3" json:"taxes,omitempty"`
	Coupons              []*Listing_Coupon         `protobuf:"bytes,7,rep,name=coupons,proto3" json:"coupons,omitempty"`
	Moderators           []string                  `protobuf:"bytes,8,rep,name=moderators,proto3" json:"moderators,omitempty"`
	TermsAndConditions   string                    `protobuf:"bytes,9,opt,name=termsAndConditions,proto3" json:"termsAndConditions,omitempty"`
	RefundPolicy         string                    `protobuf:"bytes,10,opt,name=refundPolicy,proto3" json:"refundPolicy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *Listing) Reset()         { *m = Listing{} }
func (m *Listing) String() string { return proto.CompactTextString(m) }
func (*Listing) ProtoMessage()    {}
func (*Listing) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb6b76026c8ca063, []int{0}
}

func (m *Listing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Listing.Unmarshal(m, b)
}
func (m *Listing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Listing.Marshal(b, m, deterministic)
}
func (m *Listing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Listing.Merge(m, src)
}
func (m *Listing) XXX_Size() int {
	return xxx_messageInfo_Listing.Size(m)
}
func (m *Listing) XXX_DiscardUnknown() {
	xxx_messageInfo_Listing.DiscardUnknown(m)
}

var xxx_messageInfo_Listing proto.InternalMessageInfo

func (m *Listing) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Listing) GetVendorID() *ID {
	if m != nil {
		return m.VendorID
	}
	return nil
}

func (m *Listing) GetMetadata() *Listing_Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Listing) GetItem() *Listing_Item {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *Listing) GetShippingOptions() []*Listing_ShippingOption {
	if m != nil {
		return m.ShippingOptions
	}
	return nil
}

func (m *Listing) GetTaxes() []*Listing_Tax {
	if m != nil {
		return m.Taxes
	}
	return nil
}

func (m *Listing) GetCoupons() []*Listing_Coupon {
	if m != nil {
		return m.Coupons
	}
	return nil
}

func (m *Listing) GetModerators() []string {
	if m != nil {
		return m.Moderators
	}
	return nil
}

func (m *Listing) GetTermsAndConditions() string {
	if m != nil {
		return m.TermsAndConditions
	}
	return ""
}

func (m *Listing) GetRefundPolicy() string {
	if m != nil {
		return m.RefundPolicy
	}
	return ""
}

type Listing_Metadata struct {
	Version              uint32                        `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	ContractType         Listing_Metadata_ContractType `protobuf:"varint,2,opt,name=contractType,proto3,enum=Listing_Metadata_ContractType" json:"contractType,omitempty"`
	Format               Listing_Metadata_Format       `protobuf:"varint,3,opt,name=format,proto3,enum=Listing_Metadata_Format" json:"format,omitempty"`
	Expiry               *timestamp.Timestamp          `protobuf:"bytes,4,opt,name=expiry,proto3" json:"expiry,omitempty"`
	AcceptedCurrencies   []string                      `protobuf:"bytes,5,rep,name=acceptedCurrencies,proto3" json:"acceptedCurrencies,omitempty"`
	Language             string                        `protobuf:"bytes,6,opt,name=language,proto3" json:"language,omitempty"`
	EscrowTimeoutHours   uint32                        `protobuf:"varint,7,opt,name=escrowTimeoutHours,proto3" json:"escrowTimeoutHours,omitempty"`
	PricingCurrency      *Currency                     `protobuf:"bytes,9,opt,name=pricingCurrency,proto3" json:"pricingCurrency,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *Listing_Metadata) Reset()         { *m = Listing_Metadata{} }
func (m *Listing_Metadata) String() string { return proto.CompactTextString(m) }
func (*Listing_Metadata) ProtoMessage()    {}
func (*Listing_Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb6b76026c8ca063, []int{0, 0}
}

func (m *Listing_Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Listing_Metadata.Unmarshal(m, b)
}
func (m *Listing_Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Listing_Metadata.Marshal(b, m, deterministic)
}
func (m *Listing_Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Listing_Metadata.Merge(m, src)
}
func (m *Listing_Metadata) XXX_Size() int {
	return xxx_messageInfo_Listing_Metadata.Size(m)
}
func (m *Listing_Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Listing_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Listing_Metadata proto.InternalMessageInfo

func (m *Listing_Metadata) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Listing_Metadata) GetContractType() Listing_Metadata_ContractType {
	if m != nil {
		return m.ContractType
	}
	return Listing_Metadata_PHYSICAL_GOOD
}

func (m *Listing_Metadata) GetFormat() Listing_Metadata_Format {
	if m != nil {
		return m.Format
	}
	return Listing_Metadata_FIXED_PRICE
}

func (m *Listing_Metadata) GetExpiry() *timestamp.Timestamp {
	if m != nil {
		return m.Expiry
	}
	return nil
}

func (m *Listing_Metadata) GetAcceptedCurrencies() []string {
	if m != nil {
		return m.AcceptedCurrencies
	}
	return nil
}

func (m *Listing_Metadata) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *Listing_Metadata) GetEscrowTimeoutHours() uint32 {
	if m != nil {
		return m.EscrowTimeoutHours
	}
	return 0
}

func (m *Listing_Metadata) GetPricingCurrency() *Currency {
	if m != nil {
		return m.PricingCurrency
	}
	return nil
}

type Listing_Item struct {
	Title                      string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description                string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ProcessingTime             string                 `protobuf:"bytes,3,opt,name=processingTime,proto3" json:"processingTime,omitempty"`
	Nsfw                       bool                   `protobuf:"varint,4,opt,name=nsfw,proto3" json:"nsfw,omitempty"`
	Tags                       []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Images                     []*Listing_Item_Image  `protobuf:"bytes,6,rep,name=images,proto3" json:"images,omitempty"`
	Categories                 []string               `protobuf:"bytes,7,rep,name=categories,proto3" json:"categories,omitempty"`
	Grams                      float32                `protobuf:"fixed32,8,opt,name=grams,proto3" json:"grams,omitempty"`
	Condition                  string                 `protobuf:"bytes,9,opt,name=condition,proto3" json:"condition,omitempty"`
	Options                    []*Listing_Item_Option `protobuf:"bytes,10,rep,name=options,proto3" json:"options,omitempty"`
	Skus                       []*Listing_Item_Sku    `protobuf:"bytes,11,rep,name=skus,proto3" json:"skus,omitempty"`
	Price                      string                 `protobuf:"bytes,12,opt,name=price,proto3" json:"price,omitempty"`
	CryptoListingCurrencyCode  string                 `protobuf:"bytes,13,opt,name=cryptoListingCurrencyCode,proto3" json:"cryptoListingCurrencyCode,omitempty"`
	CryptoListingPriceModifier float32                `protobuf:"fixed32,14,opt,name=cryptoListingPriceModifier,proto3" json:"cryptoListingPriceModifier,omitempty"`
	XXX_NoUnkeyedLiteral       struct{}               `json:"-"`
	XXX_unrecognized           []byte                 `json:"-"`
	XXX_sizecache              int32                  `json:"-"`
}

func (m *Listing_Item) Reset()         { *m = Listing_Item{} }
func (m *Listing_Item) String() string { return proto.CompactTextString(m) }
func (*Listing_Item) ProtoMessage()    {}
func (*Listing_Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb6b76026c8ca063, []int{0, 1}
}

func (m *Listing_Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Listing_Item.Unmarshal(m, b)
}
func (m *Listing_Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Listing_Item.Marshal(b, m, deterministic)
}
func (m *Listing_Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Listing_Item.Merge(m, src)
}
func (m *Listing_Item) XXX_Size() int {
	return xxx_messageInfo_Listing_Item.Size(m)
}
func (m *Listing_Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Listing_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Listing_Item proto.InternalMessageInfo

func (m *Listing_Item) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Listing_Item) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Listing_Item) GetProcessingTime() string {
	if m != nil {
		return m.ProcessingTime
	}
	return ""
}

func (m *Listing_Item) GetNsfw() bool {
	if m != nil {
		return m.Nsfw
	}
	return false
}

func (m *Listing_Item) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Listing_Item) GetImages() []*Listing_Item_Image {
	if m != nil {
		return m.Images
	}
	return nil
}

func (m *Listing_Item) GetCategories() []string {
	if m != nil {
		return m.Categories
	}
	return nil
}

func (m *Listing_Item) GetGrams() float32 {
	if m != nil {
		return m.Grams
	}
	return 0
}

func (m *Listing_Item) GetCondition() string {
	if m != nil {
		return m.Condition
	}
	return ""
}

func (m *Listing_Item) GetOptions() []*Listing_Item_Option {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *Listing_Item) GetSkus() []*Listing_Item_Sku {
	if m != nil {
		return m.Skus
	}
	return nil
}

func (m *Listing_Item) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *Listing_Item) GetCryptoListingCurrencyCode() string {
	if m != nil {
		return m.CryptoListingCurrencyCode
	}
	return ""
}

func (m *Listing_Item) GetCryptoListingPriceModifier() float32 {
	if m != nil {
		return m.CryptoListingPriceModifier
	}
	return 0
}

type Listing_Item_Option struct {
	Name                 string                         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string                         `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Variants             []*Listing_Item_Option_Variant `protobuf:"bytes,3,rep,name=variants,proto3" json:"variants,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *Listing_Item_Option) Reset()         { *m = Listing_Item_Option{} }
func (m *Listing_Item_Option) String() string { return proto.CompactTextString(m) }
func (*Listing_Item_Option) ProtoMessage()    {}
func (*Listing_Item_Option) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb6b76026c8ca063, []int{0, 1, 0}
}

func (m *Listing_Item_Option) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Listing_Item_Option.Unmarshal(m, b)
}
func (m *Listing_Item_Option) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Listing_Item_Option.Marshal(b, m, deterministic)
}
func (m *Listing_Item_Option) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Listing_Item_Option.Merge(m, src)
}
func (m *Listing_Item_Option) XXX_Size() int {
	return xxx_messageInfo_Listing_Item_Option.Size(m)
}
func (m *Listing_Item_Option) XXX_DiscardUnknown() {
	xxx_messageInfo_Listing_Item_Option.DiscardUnknown(m)
}

var xxx_messageInfo_Listing_Item_Option proto.InternalMessageInfo

func (m *Listing_Item_Option) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Listing_Item_Option) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Listing_Item_Option) GetVariants() []*Listing_Item_Option_Variant {
	if m != nil {
		return m.Variants
	}
	return nil
}

type Listing_Item_Option_Variant struct {
	Name                 string              `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Image                *Listing_Item_Image `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Listing_Item_Option_Variant) Reset()         { *m = Listing_Item_Option_Variant{} }
func (m *Listing_Item_Option_Variant) String() string { return proto.CompactTextString(m) }
func (*Listing_Item_Option_Variant) ProtoMessage()    {}
func (*Listing_Item_Option_Variant) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb6b76026c8ca063, []int{0, 1, 0, 0}
}

func (m *Listing_Item_Option_Variant) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Listing_Item_Option_Variant.Unmarshal(m, b)
}
func (m *Listing_Item_Option_Variant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Listing_Item_Option_Variant.Marshal(b, m, deterministic)
}
func (m *Listing_Item_Option_Variant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Listing_Item_Option_Variant.Merge(m, src)
}
func (m *Listing_Item_Option_Variant) XXX_Size() int {
	return xxx_messageInfo_Listing_Item_Option_Variant.Size(m)
}
func (m *Listing_Item_Option_Variant) XXX_DiscardUnknown() {
	xxx_messageInfo_Listing_Item_Option_Variant.DiscardUnknown(m)
}

var xxx_messageInfo_Listing_Item_Option_Variant proto.InternalMessageInfo

func (m *Listing_Item_Option_Variant) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Listing_Item_Option_Variant) GetImage() *Listing_Item_Image {
	if m != nil {
		return m.Image
	}
	return nil
}

type Listing_Item_Sku struct {
	Selections           []*Listing_Item_Sku_Selection `protobuf:"bytes,1,rep,name=selections,proto3" json:"selections,omitempty"`
	ProductID            string                        `protobuf:"bytes,2,opt,name=productID,proto3" json:"productID,omitempty"`
	Quantity             string                        `protobuf:"bytes,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Surcharge            string                        `protobuf:"bytes,4,opt,name=surcharge,proto3" json:"surcharge,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *Listing_Item_Sku) Reset()         { *m = Listing_Item_Sku{} }
func (m *Listing_Item_Sku) String() string { return proto.CompactTextString(m) }
func (*Listing_Item_Sku) ProtoMessage()    {}
func (*Listing_Item_Sku) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb6b76026c8ca063, []int{0, 1, 1}
}

func (m *Listing_Item_Sku) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Listing_Item_Sku.Unmarshal(m, b)
}
func (m *Listing_Item_Sku) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Listing_Item_Sku.Marshal(b, m, deterministic)
}
func (m *Listing_Item_Sku) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Listing_Item_Sku.Merge(m, src)
}
func (m *Listing_Item_Sku) XXX_Size() int {
	return xxx_messageInfo_Listing_Item_Sku.Size(m)
}
func (m *Listing_Item_Sku) XXX_DiscardUnknown() {
	xxx_messageInfo_Listing_Item_Sku.DiscardUnknown(m)
}

var xxx_messageInfo_Listing_Item_Sku proto.InternalMessageInfo

func (m *Listing_Item_Sku) GetSelections() []*Listing_Item_Sku_Selection {
	if m != nil {
		return m.Selections
	}
	return nil
}

func (m *Listing_Item_Sku) GetProductID() string {
	if m != nil {
		return m.ProductID
	}
	return ""
}

func (m *Listing_Item_Sku) GetQuantity() string {
	if m != nil {
		return m.Quantity
	}
	return ""
}

func (m *Listing_Item_Sku) GetSurcharge() string {
	if m != nil {
		return m.Surcharge
	}
	return ""
}

type Listing_Item_Sku_Selection struct {
	Option               string   `protobuf:"bytes,1,opt,name=option,proto3" json:"option,omitempty"`
	Variant              string   `protobuf:"bytes,2,opt,name=variant,proto3" json:"variant,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Listing_Item_Sku_Selection) Reset()         { *m = Listing_Item_Sku_Selection{} }
func (m *Listing_Item_Sku_Selection) String() string { return proto.CompactTextString(m) }
func (*Listing_Item_Sku_Selection) ProtoMessage()    {}
func (*Listing_Item_Sku_Selection) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb6b76026c8ca063, []int{0, 1, 1, 0}
}

func (m *Listing_Item_Sku_Selection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Listing_Item_Sku_Selection.Unmarshal(m, b)
}
func (m *Listing_Item_Sku_Selection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Listing_Item_Sku_Selection.Marshal(b, m, deterministic)
}
func (m *Listing_Item_Sku_Selection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Listing_Item_Sku_Selection.Merge(m, src)
}
func (m *Listing_Item_Sku_Selection) XXX_Size() int {
	return xxx_messageInfo_Listing_Item_Sku_Selection.Size(m)
}
func (m *Listing_Item_Sku_Selection) XXX_DiscardUnknown() {
	xxx_messageInfo_Listing_Item_Sku_Selection.DiscardUnknown(m)
}

var xxx_messageInfo_Listing_Item_Sku_Selection proto.InternalMessageInfo

func (m *Listing_Item_Sku_Selection) GetOption() string {
	if m != nil {
		return m.Option
	}
	return ""
}

func (m *Listing_Item_Sku_Selection) GetVariant() string {
	if m != nil {
		return m.Variant
	}
	return ""
}

type Listing_Item_Image struct {
	Filename             string   `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Original             string   `protobuf:"bytes,2,opt,name=original,proto3" json:"original,omitempty"`
	Large                string   `protobuf:"bytes,3,opt,name=large,proto3" json:"large,omitempty"`
	Medium               string   `protobuf:"bytes,4,opt,name=medium,proto3" json:"medium,omitempty"`
	Small                string   `protobuf:"bytes,5,opt,name=small,proto3" json:"small,omitempty"`
	Tiny                 string   `protobuf:"bytes,6,opt,name=tiny,proto3" json:"tiny,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Listing_Item_Image) Reset()         { *m = Listing_Item_Image{} }
func (m *Listing_Item_Image) String() string { return proto.CompactTextString(m) }
func (*Listing_Item_Image) ProtoMessage()    {}
func (*Listing_Item_Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb6b76026c8ca063, []int{0, 1, 2}
}

func (m *Listing_Item_Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Listing_Item_Image.Unmarshal(m, b)
}
func (m *Listing_Item_Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Listing_Item_Image.Marshal(b, m, deterministic)
}
func (m *Listing_Item_Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Listing_Item_Image.Merge(m, src)
}
func (m *Listing_Item_Image) XXX_Size() int {
	return xxx_messageInfo_Listing_Item_Image.Size(m)
}
func (m *Listing_Item_Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Listing_Item_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Listing_Item_Image proto.InternalMessageInfo

func (m *Listing_Item_Image) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *Listing_Item_Image) GetOriginal() string {
	if m != nil {
		return m.Original
	}
	return ""
}

func (m *Listing_Item_Image) GetLarge() string {
	if m != nil {
		return m.Large
	}
	return ""
}

func (m *Listing_Item_Image) GetMedium() string {
	if m != nil {
		return m.Medium
	}
	return ""
}

func (m *Listing_Item_Image) GetSmall() string {
	if m != nil {
		return m.Small
	}
	return ""
}

func (m *Listing_Item_Image) GetTiny() string {
	if m != nil {
		return m.Tiny
	}
	return ""
}

type Listing_ShippingOption struct {
	Name                 string                              `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 Listing_ShippingOption_ShippingType `protobuf:"varint,2,opt,name=type,proto3,enum=Listing_ShippingOption_ShippingType" json:"type,omitempty"`
	Regions              []CountryCode                       `protobuf:"varint,3,rep,packed,name=regions,proto3,enum=CountryCode" json:"regions,omitempty"`
	Services             []*Listing_ShippingOption_Service   `protobuf:"bytes,4,rep,name=services,proto3" json:"services,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *Listing_ShippingOption) Reset()         { *m = Listing_ShippingOption{} }
func (m *Listing_ShippingOption) String() string { return proto.CompactTextString(m) }
func (*Listing_ShippingOption) ProtoMessage()    {}
func (*Listing_ShippingOption) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb6b76026c8ca063, []int{0, 2}
}

func (m *Listing_ShippingOption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Listing_ShippingOption.Unmarshal(m, b)
}
func (m *Listing_ShippingOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Listing_ShippingOption.Marshal(b, m, deterministic)
}
func (m *Listing_ShippingOption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Listing_ShippingOption.Merge(m, src)
}
func (m *Listing_ShippingOption) XXX_Size() int {
	return xxx_messageInfo_Listing_ShippingOption.Size(m)
}
func (m *Listing_ShippingOption) XXX_DiscardUnknown() {
	xxx_messageInfo_Listing_ShippingOption.DiscardUnknown(m)
}

var xxx_messageInfo_Listing_ShippingOption proto.InternalMessageInfo

func (m *Listing_ShippingOption) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Listing_ShippingOption) GetType() Listing_ShippingOption_ShippingType {
	if m != nil {
		return m.Type
	}
	return Listing_ShippingOption_LOCAL_PICKUP
}

func (m *Listing_ShippingOption) GetRegions() []CountryCode {
	if m != nil {
		return m.Regions
	}
	return nil
}

func (m *Listing_ShippingOption) GetServices() []*Listing_ShippingOption_Service {
	if m != nil {
		return m.Services
	}
	return nil
}

type Listing_ShippingOption_Service struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	EstimatedDelivery    string   `protobuf:"bytes,2,opt,name=estimatedDelivery,proto3" json:"estimatedDelivery,omitempty"`
	Price                string   `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	AdditionalItemPrice  string   `protobuf:"bytes,4,opt,name=additionalItemPrice,proto3" json:"additionalItemPrice,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Listing_ShippingOption_Service) Reset()         { *m = Listing_ShippingOption_Service{} }
func (m *Listing_ShippingOption_Service) String() string { return proto.CompactTextString(m) }
func (*Listing_ShippingOption_Service) ProtoMessage()    {}
func (*Listing_ShippingOption_Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb6b76026c8ca063, []int{0, 2, 0}
}

func (m *Listing_ShippingOption_Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Listing_ShippingOption_Service.Unmarshal(m, b)
}
func (m *Listing_ShippingOption_Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Listing_ShippingOption_Service.Marshal(b, m, deterministic)
}
func (m *Listing_ShippingOption_Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Listing_ShippingOption_Service.Merge(m, src)
}
func (m *Listing_ShippingOption_Service) XXX_Size() int {
	return xxx_messageInfo_Listing_ShippingOption_Service.Size(m)
}
func (m *Listing_ShippingOption_Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Listing_ShippingOption_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Listing_ShippingOption_Service proto.InternalMessageInfo

func (m *Listing_ShippingOption_Service) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Listing_ShippingOption_Service) GetEstimatedDelivery() string {
	if m != nil {
		return m.EstimatedDelivery
	}
	return ""
}

func (m *Listing_ShippingOption_Service) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *Listing_ShippingOption_Service) GetAdditionalItemPrice() string {
	if m != nil {
		return m.AdditionalItemPrice
	}
	return ""
}

type Listing_Tax struct {
	TaxType              string        `protobuf:"bytes,1,opt,name=taxType,proto3" json:"taxType,omitempty"`
	TaxRegions           []CountryCode `protobuf:"varint,2,rep,packed,name=taxRegions,proto3,enum=CountryCode" json:"taxRegions,omitempty"`
	TaxShipping          bool          `protobuf:"varint,3,opt,name=taxShipping,proto3" json:"taxShipping,omitempty"`
	Percentage           float32       `protobuf:"fixed32,4,opt,name=percentage,proto3" json:"percentage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Listing_Tax) Reset()         { *m = Listing_Tax{} }
func (m *Listing_Tax) String() string { return proto.CompactTextString(m) }
func (*Listing_Tax) ProtoMessage()    {}
func (*Listing_Tax) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb6b76026c8ca063, []int{0, 3}
}

func (m *Listing_Tax) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Listing_Tax.Unmarshal(m, b)
}
func (m *Listing_Tax) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Listing_Tax.Marshal(b, m, deterministic)
}
func (m *Listing_Tax) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Listing_Tax.Merge(m, src)
}
func (m *Listing_Tax) XXX_Size() int {
	return xxx_messageInfo_Listing_Tax.Size(m)
}
func (m *Listing_Tax) XXX_DiscardUnknown() {
	xxx_messageInfo_Listing_Tax.DiscardUnknown(m)
}

var xxx_messageInfo_Listing_Tax proto.InternalMessageInfo

func (m *Listing_Tax) GetTaxType() string {
	if m != nil {
		return m.TaxType
	}
	return ""
}

func (m *Listing_Tax) GetTaxRegions() []CountryCode {
	if m != nil {
		return m.TaxRegions
	}
	return nil
}

func (m *Listing_Tax) GetTaxShipping() bool {
	if m != nil {
		return m.TaxShipping
	}
	return false
}

func (m *Listing_Tax) GetPercentage() float32 {
	if m != nil {
		return m.Percentage
	}
	return 0
}

type Listing_Coupon struct {
	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	// Types that are valid to be assigned to Code:
	//	*Listing_Coupon_Hash
	//	*Listing_Coupon_DiscountCode
	Code isListing_Coupon_Code `protobuf_oneof:"code"`
	// Types that are valid to be assigned to Discount:
	//	*Listing_Coupon_PercentDiscount
	//	*Listing_Coupon_PriceDiscount
	Discount             isListing_Coupon_Discount `protobuf_oneof:"discount"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *Listing_Coupon) Reset()         { *m = Listing_Coupon{} }
func (m *Listing_Coupon) String() string { return proto.CompactTextString(m) }
func (*Listing_Coupon) ProtoMessage()    {}
func (*Listing_Coupon) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb6b76026c8ca063, []int{0, 4}
}

func (m *Listing_Coupon) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Listing_Coupon.Unmarshal(m, b)
}
func (m *Listing_Coupon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Listing_Coupon.Marshal(b, m, deterministic)
}
func (m *Listing_Coupon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Listing_Coupon.Merge(m, src)
}
func (m *Listing_Coupon) XXX_Size() int {
	return xxx_messageInfo_Listing_Coupon.Size(m)
}
func (m *Listing_Coupon) XXX_DiscardUnknown() {
	xxx_messageInfo_Listing_Coupon.DiscardUnknown(m)
}

var xxx_messageInfo_Listing_Coupon proto.InternalMessageInfo

func (m *Listing_Coupon) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type isListing_Coupon_Code interface {
	isListing_Coupon_Code()
}

type Listing_Coupon_Hash struct {
	Hash string `protobuf:"bytes,2,opt,name=hash,proto3,oneof"`
}

type Listing_Coupon_DiscountCode struct {
	DiscountCode string `protobuf:"bytes,3,opt,name=discountCode,proto3,oneof"`
}

func (*Listing_Coupon_Hash) isListing_Coupon_Code() {}

func (*Listing_Coupon_DiscountCode) isListing_Coupon_Code() {}

func (m *Listing_Coupon) GetCode() isListing_Coupon_Code {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *Listing_Coupon) GetHash() string {
	if x, ok := m.GetCode().(*Listing_Coupon_Hash); ok {
		return x.Hash
	}
	return ""
}

func (m *Listing_Coupon) GetDiscountCode() string {
	if x, ok := m.GetCode().(*Listing_Coupon_DiscountCode); ok {
		return x.DiscountCode
	}
	return ""
}

type isListing_Coupon_Discount interface {
	isListing_Coupon_Discount()
}

type Listing_Coupon_PercentDiscount struct {
	PercentDiscount float32 `protobuf:"fixed32,4,opt,name=percentDiscount,proto3,oneof"`
}

type Listing_Coupon_PriceDiscount struct {
	PriceDiscount string `protobuf:"bytes,5,opt,name=priceDiscount,proto3,oneof"`
}

func (*Listing_Coupon_PercentDiscount) isListing_Coupon_Discount() {}

func (*Listing_Coupon_PriceDiscount) isListing_Coupon_Discount() {}

func (m *Listing_Coupon) GetDiscount() isListing_Coupon_Discount {
	if m != nil {
		return m.Discount
	}
	return nil
}

func (m *Listing_Coupon) GetPercentDiscount() float32 {
	if x, ok := m.GetDiscount().(*Listing_Coupon_PercentDiscount); ok {
		return x.PercentDiscount
	}
	return 0
}

func (m *Listing_Coupon) GetPriceDiscount() string {
	if x, ok := m.GetDiscount().(*Listing_Coupon_PriceDiscount); ok {
		return x.PriceDiscount
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Listing_Coupon) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Listing_Coupon_Hash)(nil),
		(*Listing_Coupon_DiscountCode)(nil),
		(*Listing_Coupon_PercentDiscount)(nil),
		(*Listing_Coupon_PriceDiscount)(nil),
	}
}

type SignedListing struct {
	Listing              *Listing `protobuf:"bytes,1,opt,name=listing,proto3" json:"listing,omitempty"`
	Cid                  string   `protobuf:"bytes,2,opt,name=cid,proto3" json:"cid,omitempty"`
	Signature            []byte   `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignedListing) Reset()         { *m = SignedListing{} }
func (m *SignedListing) String() string { return proto.CompactTextString(m) }
func (*SignedListing) ProtoMessage()    {}
func (*SignedListing) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb6b76026c8ca063, []int{1}
}

func (m *SignedListing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedListing.Unmarshal(m, b)
}
func (m *SignedListing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedListing.Marshal(b, m, deterministic)
}
func (m *SignedListing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedListing.Merge(m, src)
}
func (m *SignedListing) XXX_Size() int {
	return xxx_messageInfo_SignedListing.Size(m)
}
func (m *SignedListing) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedListing.DiscardUnknown(m)
}

var xxx_messageInfo_SignedListing proto.InternalMessageInfo

func (m *SignedListing) GetListing() *Listing {
	if m != nil {
		return m.Listing
	}
	return nil
}

func (m *SignedListing) GetCid() string {
	if m != nil {
		return m.Cid
	}
	return ""
}

func (m *SignedListing) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func init() {
	proto.RegisterEnum("Listing_Metadata_ContractType", Listing_Metadata_ContractType_name, Listing_Metadata_ContractType_value)
	proto.RegisterEnum("Listing_Metadata_Format", Listing_Metadata_Format_name, Listing_Metadata_Format_value)
	proto.RegisterEnum("Listing_ShippingOption_ShippingType", Listing_ShippingOption_ShippingType_name, Listing_ShippingOption_ShippingType_value)
	proto.RegisterType((*Listing)(nil), "Listing")
	proto.RegisterType((*Listing_Metadata)(nil), "Listing.Metadata")
	proto.RegisterType((*Listing_Item)(nil), "Listing.Item")
	proto.RegisterType((*Listing_Item_Option)(nil), "Listing.Item.Option")
	proto.RegisterType((*Listing_Item_Option_Variant)(nil), "Listing.Item.Option.Variant")
	proto.RegisterType((*Listing_Item_Sku)(nil), "Listing.Item.Sku")
	proto.RegisterType((*Listing_Item_Sku_Selection)(nil), "Listing.Item.Sku.Selection")
	proto.RegisterType((*Listing_Item_Image)(nil), "Listing.Item.Image")
	proto.RegisterType((*Listing_ShippingOption)(nil), "Listing.ShippingOption")
	proto.RegisterType((*Listing_ShippingOption_Service)(nil), "Listing.ShippingOption.Service")
	proto.RegisterType((*Listing_Tax)(nil), "Listing.Tax")
	proto.RegisterType((*Listing_Coupon)(nil), "Listing.Coupon")
	proto.RegisterType((*SignedListing)(nil), "SignedListing")
}

func init() { proto.RegisterFile("listing.proto", fileDescriptor_eb6b76026c8ca063) }

var fileDescriptor_eb6b76026c8ca063 = []byte{
	// 1335 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x56, 0xdd, 0x6e, 0x1b, 0x37,
	0x16, 0x8e, 0x2c, 0x59, 0x3f, 0x47, 0xb2, 0x6c, 0x33, 0xd9, 0xdd, 0xd9, 0xd9, 0x20, 0xf1, 0x0a,
	0x69, 0xe0, 0x34, 0xe9, 0x24, 0x55, 0x6e, 0x02, 0xa4, 0x2d, 0x60, 0x4b, 0x4e, 0x2c, 0xe4, 0xc7,
	0x06, 0xed, 0xa4, 0x4d, 0x6f, 0x02, 0x66, 0x86, 0x1e, 0x13, 0x99, 0x19, 0x4e, 0x39, 0x1c, 0xc7,
	0x7a, 0x87, 0x02, 0x05, 0xda, 0x8b, 0x3e, 0x49, 0x5f, 0xa0, 0x77, 0x7d, 0x84, 0xbe, 0x4d, 0xc1,
	0x33, 0x9c, 0x91, 0x64, 0xcb, 0x45, 0xef, 0x78, 0xbe, 0xf3, 0x91, 0x3c, 0xff, 0x24, 0xac, 0x45,
	0x22, 0xd3, 0x22, 0x09, 0xbd, 0x54, 0x49, 0x2d, 0x5d, 0xe2, 0xcb, 0x3c, 0xd1, 0x6a, 0xea, 0xcb,
	0x80, 0x67, 0x16, 0xeb, 0xf9, 0x32, 0x8e, 0x65, 0x62, 0xa5, 0xdb, 0xa1, 0x94, 0x61, 0xc4, 0x1f,
	0xa2, 0xf4, 0x21, 0x3f, 0x79, 0xa8, 0x45, 0xcc, 0x33, 0xcd, 0xe2, 0xb4, 0x20, 0x0c, 0xfe, 0xf8,
	0x17, 0xb4, 0x5e, 0x16, 0x87, 0x12, 0x02, 0x8d, 0x2c, 0xca, 0x43, 0xa7, 0xb6, 0x55, 0xdb, 0xee,
	0x50, 0x5c, 0x93, 0xdb, 0xd0, 0x3e, 0xe3, 0x49, 0x20, 0xd5, 0x64, 0xec, 0xac, 0x6c, 0xd5, 0xb6,
	0xbb, 0xc3, 0xba, 0x37, 0x19, 0xd3, 0x0a, 0x24, 0x5f, 0x40, 0x3b, 0xe6, 0x9a, 0x05, 0x4c, 0x33,
	0xa7, 0x8e, 0x84, 0x4d, 0xcf, 0x1e, 0xe8, 0xbd, 0xb2, 0x0a, 0x5a, 0x51, 0xc8, 0xff, 0xa1, 0x21,
	0x34, 0x8f, 0x9d, 0x06, 0x52, 0xd7, 0x2a, 0xea, 0x44, 0xf3, 0x98, 0xa2, 0x8a, 0xec, 0xc0, 0x7a,
	0x76, 0x2a, 0xd2, 0x54, 0x24, 0xe1, 0x41, 0xaa, 0x85, 0x4c, 0x32, 0x67, 0x75, 0xab, 0xbe, 0xdd,
	0x1d, 0xfe, 0xa7, 0x62, 0x1f, 0x2d, 0xe8, 0xe9, 0x45, 0x3e, 0x19, 0xc0, 0xaa, 0x66, 0xe7, 0x3c,
	0x73, 0x9a, 0xb8, 0xb1, 0x57, 0x6d, 0x3c, 0x66, 0xe7, 0xb4, 0x50, 0x91, 0x7b, 0xd0, 0xf2, 0x65,
	0x9e, 0x9a, 0xe3, 0x5b, 0xc8, 0x5a, 0xaf, 0x58, 0x23, 0xc4, 0x69, 0xa9, 0x27, 0xb7, 0x00, 0x62,
	0x19, 0x70, 0xc5, 0xb4, 0x54, 0x99, 0xd3, 0xde, 0xaa, 0x6f, 0x77, 0xe8, 0x1c, 0x42, 0x3c, 0x20,
	0x9a, 0xab, 0x38, 0xdb, 0x49, 0x82, 0x91, 0x4c, 0x02, 0x51, 0x18, 0xdd, 0xc1, 0x30, 0x2e, 0xd1,
	0x90, 0x01, 0xf4, 0x14, 0x3f, 0xc9, 0x93, 0xe0, 0x50, 0x46, 0xc2, 0x9f, 0x3a, 0x80, 0xcc, 0x05,
	0xcc, 0xfd, 0xb9, 0x01, 0xed, 0x32, 0x7e, 0xc4, 0x81, 0xd6, 0x19, 0x57, 0x99, 0x90, 0x09, 0x26,
	0x67, 0x8d, 0x96, 0x22, 0xd9, 0x85, 0x9e, 0x2f, 0x13, 0xad, 0x98, 0xaf, 0x8f, 0xa7, 0x29, 0xc7,
	0x1c, 0xf5, 0x87, 0xb7, 0x2e, 0xa5, 0xc0, 0x1b, 0xcd, 0xb1, 0xe8, 0xc2, 0x1e, 0xf2, 0x08, 0x9a,
	0x27, 0x52, 0xc5, 0x4c, 0x63, 0x02, 0xfb, 0x43, 0xe7, 0xf2, 0xee, 0x67, 0xa8, 0xa7, 0x96, 0x47,
	0x86, 0xd0, 0xe4, 0xe7, 0xa9, 0x50, 0x53, 0x9b, 0x47, 0xd7, 0x2b, 0xea, 0xcc, 0x2b, 0xeb, 0xcc,
	0x3b, 0x2e, 0xeb, 0x8c, 0x5a, 0xa6, 0x09, 0x12, 0xf3, 0x7d, 0x9e, 0x6a, 0x1e, 0x8c, 0x72, 0xa5,
	0x78, 0xe2, 0x0b, 0x5e, 0x64, 0xb6, 0x43, 0x97, 0x68, 0x88, 0x0b, 0xed, 0x88, 0x25, 0x61, 0xce,
	0x42, 0xee, 0x34, 0x31, 0x40, 0x95, 0x6c, 0xce, 0xe2, 0x99, 0xaf, 0xe4, 0x27, 0x73, 0x8d, 0xcc,
	0xf5, 0xbe, 0xcc, 0x95, 0x49, 0xa3, 0x09, 0xcd, 0x12, 0x0d, 0x79, 0x0c, 0xeb, 0xa9, 0x12, 0xbe,
	0x48, 0x42, 0x7b, 0xc1, 0x14, 0xb3, 0xd3, 0x1d, 0x76, 0xbc, 0x12, 0xa0, 0x17, 0x19, 0x83, 0x00,
	0x7a, 0xf3, 0x41, 0x23, 0x9b, 0xb0, 0x76, 0xb8, 0xff, 0xee, 0x68, 0x32, 0xda, 0x79, 0xf9, 0xfe,
	0xf9, 0xc1, 0xc1, 0x78, 0xe3, 0x1a, 0xd9, 0x80, 0xde, 0x78, 0xf2, 0x7c, 0x72, 0x5c, 0x22, 0x35,
	0xd2, 0x85, 0xd6, 0xd1, 0x1e, 0x7d, 0x3b, 0x19, 0xed, 0x6d, 0xac, 0x90, 0x3e, 0xc0, 0x88, 0x1e,
	0x7c, 0x3b, 0x7e, 0xff, 0xec, 0xcd, 0xeb, 0xf1, 0x46, 0x9d, 0x10, 0xe8, 0x8f, 0xe8, 0xbb, 0xc3,
	0xe3, 0x83, 0xd1, 0x1b, 0x4a, 0xf7, 0x5e, 0x8f, 0xde, 0x6d, 0x34, 0x06, 0xf7, 0xa1, 0x59, 0x04,
	0x97, 0xac, 0x43, 0xf7, 0xd9, 0xe4, 0xbb, 0xbd, 0xf1, 0xfb, 0x43, 0x6a, 0xb6, 0xe3, 0xe9, 0xaf,
	0x76, 0xe8, 0x8b, 0xbd, 0x63, 0x8b, 0xac, 0xb8, 0xbf, 0xb5, 0xa1, 0x61, 0x3a, 0x85, 0xdc, 0x80,
	0x55, 0x2d, 0x74, 0xc4, 0x6d, 0xaf, 0x16, 0x02, 0xd9, 0x82, 0x6e, 0x60, 0xbc, 0x17, 0xd8, 0x06,
	0x58, 0x0b, 0x1d, 0x3a, 0x0f, 0x91, 0xbb, 0xd0, 0x4f, 0x95, 0xf4, 0x79, 0x96, 0x89, 0x24, 0x34,
	0x21, 0xc2, 0x94, 0x77, 0xe8, 0x05, 0xd4, 0x8c, 0x82, 0x24, 0x3b, 0xf9, 0x84, 0xe9, 0x6d, 0x53,
	0x5c, 0x1b, 0x4c, 0xb3, 0xb0, 0x4c, 0x19, 0xae, 0xc9, 0x7d, 0x68, 0x8a, 0x98, 0x85, 0x55, 0xa7,
	0x5d, 0x5f, 0x68, 0x68, 0x6f, 0x62, 0x74, 0xd4, 0x52, 0x4c, 0x1b, 0xf9, 0x4c, 0xf3, 0x50, 0x2a,
	0x93, 0xf9, 0x56, 0xd1, 0x46, 0x33, 0xc4, 0x38, 0x15, 0x2a, 0x16, 0x9b, 0x0e, 0xab, 0x6d, 0xaf,
	0xd0, 0x42, 0x20, 0x37, 0xa1, 0xe3, 0x97, 0xad, 0x63, 0x7b, 0x6a, 0x06, 0x10, 0x0f, 0x5a, 0xd2,
	0x0e, 0x09, 0x40, 0x0b, 0x6e, 0x2c, 0x5a, 0x60, 0x27, 0x44, 0x49, 0x22, 0x9f, 0x41, 0x23, 0xfb,
	0x98, 0x67, 0x4e, 0x17, 0xc9, 0x9b, 0x8b, 0xe4, 0xa3, 0x8f, 0x39, 0x45, 0xb5, 0x31, 0xc5, 0x94,
	0x03, 0x77, 0x7a, 0x45, 0x7c, 0x51, 0x20, 0x5f, 0xc1, 0x7f, 0x7d, 0x35, 0x4d, 0xb5, 0xb4, 0xbb,
	0xca, 0x52, 0x19, 0xc9, 0x80, 0x3b, 0x6b, 0xc8, 0xbc, 0x9a, 0x40, 0xbe, 0x01, 0x77, 0x41, 0x79,
	0x68, 0xce, 0x7c, 0x25, 0x03, 0x71, 0x22, 0xb8, 0x72, 0xfa, 0xe8, 0xf3, 0xdf, 0x30, 0xdc, 0xdf,
	0x6b, 0xd0, 0x2c, 0xdc, 0xc1, 0xf4, 0xb0, 0xb8, 0xcc, 0x3e, 0xae, 0xff, 0x41, 0xf2, 0x9f, 0x40,
	0xfb, 0x8c, 0x29, 0xc1, 0x12, 0x9d, 0x39, 0x75, 0xf4, 0xff, 0xe6, 0xb2, 0x60, 0x79, 0x6f, 0x0b,
	0x12, 0xad, 0xd8, 0xee, 0x3e, 0xb4, 0x2c, 0xb8, 0xf4, 0xea, 0x7b, 0xb0, 0x8a, 0x29, 0xb6, 0x2f,
	0xc4, 0xd2, 0x22, 0x28, 0x18, 0xee, 0x9f, 0x35, 0xa8, 0x1f, 0x7d, 0xcc, 0xc9, 0x53, 0x80, 0x8c,
	0x47, 0xdc, 0x2f, 0x52, 0x57, 0x43, 0x6b, 0xfe, 0x77, 0x29, 0x1b, 0xde, 0x51, 0xc9, 0xa1, 0x73,
	0x74, 0x53, 0x12, 0xa9, 0x92, 0x41, 0xee, 0x6b, 0xfb, 0x2a, 0x75, 0xe8, 0x0c, 0x30, 0x83, 0xe3,
	0x87, 0x9c, 0x25, 0x5a, 0xe8, 0xa9, 0xad, 0xee, 0x4a, 0x36, 0x3b, 0xb3, 0x5c, 0xf9, 0xa7, 0x4c,
	0x85, 0x1c, 0x8b, 0xbb, 0x43, 0x67, 0x80, 0xfb, 0x35, 0x74, 0xaa, 0x0b, 0xc9, 0xbf, 0xa1, 0x59,
	0x14, 0x8d, 0x75, 0xd5, 0x4a, 0x38, 0x8b, 0x8b, 0x58, 0xd8, 0xab, 0x4b, 0xd1, 0xfd, 0xb5, 0x06,
	0xab, 0xe8, 0xac, 0x31, 0xe1, 0x44, 0x44, 0x7c, 0x2e, 0x50, 0x95, 0x6c, 0x74, 0x52, 0x89, 0x50,
	0x24, 0x2c, 0xb2, 0x07, 0x54, 0xb2, 0x29, 0xbb, 0x08, 0x4d, 0x2b, 0xec, 0x2e, 0x04, 0x63, 0x49,
	0xcc, 0x03, 0x91, 0xc7, 0xd6, 0x62, 0x2b, 0x19, 0x76, 0x16, 0xb3, 0x28, 0x72, 0x56, 0x0b, 0x36,
	0x0a, 0xd8, 0xa6, 0x22, 0x99, 0xda, 0x99, 0x89, 0x6b, 0xf7, 0xc7, 0x3a, 0xf4, 0x17, 0xdf, 0xcc,
	0xa5, 0x79, 0x7c, 0x02, 0x0d, 0x3d, 0x7b, 0x44, 0xee, 0x5c, 0xf1, 0xdc, 0x56, 0x22, 0x3e, 0x25,
	0xb8, 0x83, 0xdc, 0x85, 0x96, 0xe2, 0x21, 0xe6, 0xd2, 0x54, 0x56, 0x7f, 0xd8, 0x33, 0x8f, 0xa8,
	0xf9, 0x9b, 0x98, 0xd2, 0xa7, 0xa5, 0x92, 0x3c, 0x85, 0x76, 0xc6, 0xd5, 0x99, 0xf0, 0x79, 0xe6,
	0x34, 0x30, 0xe9, 0xb7, 0xaf, 0xbc, 0xa5, 0xe0, 0xd1, 0x6a, 0x83, 0xfb, 0x4b, 0x0d, 0x5a, 0x16,
	0x5d, 0x6a, 0xfe, 0x03, 0xd8, 0xe4, 0x99, 0x16, 0x31, 0xd3, 0x3c, 0x18, 0xf3, 0x48, 0x9c, 0x71,
	0x35, 0xb5, 0x21, 0xbe, 0xac, 0x98, 0xb5, 0x78, 0x7d, 0xbe, 0xc5, 0x1f, 0xc1, 0x75, 0x16, 0x14,
	0xb3, 0x85, 0x45, 0xa6, 0x0c, 0xb1, 0x07, 0x6d, 0xe0, 0x97, 0xa9, 0x06, 0x5f, 0x42, 0x6f, 0x3e,
	0x20, 0x66, 0x6a, 0xbf, 0x3c, 0x30, 0x6f, 0xc4, 0xe1, 0x64, 0xf4, 0xe2, 0xcd, 0xe1, 0xc6, 0xb5,
	0x8b, 0x83, 0xbd, 0xe6, 0xfe, 0x54, 0x83, 0xfa, 0x31, 0x3b, 0x37, 0xa5, 0xa4, 0xd9, 0x39, 0xbe,
	0xdb, 0x85, 0x1f, 0xa5, 0x48, 0x1e, 0x00, 0x68, 0x76, 0x4e, 0x6d, 0x48, 0x57, 0x96, 0x84, 0x74,
	0x4e, 0x6f, 0x5a, 0x5f, 0xb3, 0xf3, 0xd2, 0x0a, 0x74, 0xa8, 0x4d, 0xe7, 0x21, 0x33, 0x7a, 0x53,
	0xae, 0x7c, 0x9e, 0x68, 0x66, 0x0b, 0x7f, 0x85, 0xce, 0x21, 0x38, 0x5b, 0x8a, 0x5f, 0xcf, 0x15,
	0x4f, 0xcb, 0x0d, 0x68, 0x9c, 0xb2, 0xec, 0xb4, 0x08, 0xe7, 0xfe, 0x35, 0x8a, 0x12, 0xb9, 0x03,
	0xbd, 0x40, 0x64, 0xf8, 0x0b, 0xc5, 0x19, 0x58, 0xb7, 0xda, 0x05, 0x94, 0x7c, 0x0e, 0xeb, 0xf6,
	0xaa, 0xb1, 0x85, 0x0b, 0x0b, 0xf6, 0x6b, 0xf4, 0xa2, 0x82, 0xdc, 0x85, 0x35, 0x4c, 0x44, 0xc5,
	0xc4, 0xda, 0xde, 0xaf, 0xd1, 0x45, 0x78, 0xb7, 0x09, 0x0d, 0xf3, 0xeb, 0xdd, 0x05, 0x68, 0x97,
	0x77, 0x0d, 0x7c, 0x58, 0x3b, 0x12, 0x61, 0xc2, 0x83, 0xf2, 0x43, 0x3b, 0x80, 0x96, 0xfd, 0x30,
	0xa3, 0x33, 0xdd, 0x61, 0xbb, 0x2c, 0x36, 0x5a, 0x2a, 0xc8, 0x06, 0xd4, 0x7d, 0x11, 0xd8, 0x32,
	0x31, 0x4b, 0x9c, 0x11, 0x22, 0x4c, 0x98, 0xce, 0x55, 0xe1, 0x51, 0x8f, 0xce, 0x80, 0xdd, 0xc6,
	0xf7, 0x2b, 0xe9, 0x87, 0x0f, 0x4d, 0xfc, 0xe8, 0x3c, 0xfe, 0x2b, 0x00, 0x00, 0xff, 0xff, 0xa2,
	0xf8, 0xd5, 0xc6, 0x91, 0x0b, 0x00, 0x00,
}
