// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: listing.proto

package pb

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Listing_Metadata_ContractType int32

const (
	Listing_Metadata_PHYSICAL_GOOD  Listing_Metadata_ContractType = 0
	Listing_Metadata_DIGITAL_GOOD   Listing_Metadata_ContractType = 1
	Listing_Metadata_SERVICE        Listing_Metadata_ContractType = 2
	Listing_Metadata_CLASSIFIED     Listing_Metadata_ContractType = 3
	Listing_Metadata_CRYPTOCURRENCY Listing_Metadata_ContractType = 4
)

// Enum value maps for Listing_Metadata_ContractType.
var (
	Listing_Metadata_ContractType_name = map[int32]string{
		0: "PHYSICAL_GOOD",
		1: "DIGITAL_GOOD",
		2: "SERVICE",
		3: "CLASSIFIED",
		4: "CRYPTOCURRENCY",
	}
	Listing_Metadata_ContractType_value = map[string]int32{
		"PHYSICAL_GOOD":  0,
		"DIGITAL_GOOD":   1,
		"SERVICE":        2,
		"CLASSIFIED":     3,
		"CRYPTOCURRENCY": 4,
	}
)

func (x Listing_Metadata_ContractType) Enum() *Listing_Metadata_ContractType {
	p := new(Listing_Metadata_ContractType)
	*p = x
	return p
}

func (x Listing_Metadata_ContractType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Listing_Metadata_ContractType) Descriptor() protoreflect.EnumDescriptor {
	return file_listing_proto_enumTypes[0].Descriptor()
}

func (Listing_Metadata_ContractType) Type() protoreflect.EnumType {
	return &file_listing_proto_enumTypes[0]
}

func (x Listing_Metadata_ContractType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Listing_Metadata_ContractType.Descriptor instead.
func (Listing_Metadata_ContractType) EnumDescriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{0, 0, 0}
}

type Listing_Metadata_Format int32

const (
	Listing_Metadata_FIXED_PRICE  Listing_Metadata_Format = 0
	Listing_Metadata_MARKET_PRICE Listing_Metadata_Format = 1
)

// Enum value maps for Listing_Metadata_Format.
var (
	Listing_Metadata_Format_name = map[int32]string{
		0: "FIXED_PRICE",
		1: "MARKET_PRICE",
	}
	Listing_Metadata_Format_value = map[string]int32{
		"FIXED_PRICE":  0,
		"MARKET_PRICE": 1,
	}
)

func (x Listing_Metadata_Format) Enum() *Listing_Metadata_Format {
	p := new(Listing_Metadata_Format)
	*p = x
	return p
}

func (x Listing_Metadata_Format) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Listing_Metadata_Format) Descriptor() protoreflect.EnumDescriptor {
	return file_listing_proto_enumTypes[1].Descriptor()
}

func (Listing_Metadata_Format) Type() protoreflect.EnumType {
	return &file_listing_proto_enumTypes[1]
}

func (x Listing_Metadata_Format) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Listing_Metadata_Format.Descriptor instead.
func (Listing_Metadata_Format) EnumDescriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{0, 0, 1}
}

type Listing_ShippingOption_ShippingType int32

const (
	Listing_ShippingOption_LOCAL_PICKUP Listing_ShippingOption_ShippingType = 0
	Listing_ShippingOption_FIXED_PRICE  Listing_ShippingOption_ShippingType = 1
)

// Enum value maps for Listing_ShippingOption_ShippingType.
var (
	Listing_ShippingOption_ShippingType_name = map[int32]string{
		0: "LOCAL_PICKUP",
		1: "FIXED_PRICE",
	}
	Listing_ShippingOption_ShippingType_value = map[string]int32{
		"LOCAL_PICKUP": 0,
		"FIXED_PRICE":  1,
	}
)

func (x Listing_ShippingOption_ShippingType) Enum() *Listing_ShippingOption_ShippingType {
	p := new(Listing_ShippingOption_ShippingType)
	*p = x
	return p
}

func (x Listing_ShippingOption_ShippingType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Listing_ShippingOption_ShippingType) Descriptor() protoreflect.EnumDescriptor {
	return file_listing_proto_enumTypes[2].Descriptor()
}

func (Listing_ShippingOption_ShippingType) Type() protoreflect.EnumType {
	return &file_listing_proto_enumTypes[2]
}

func (x Listing_ShippingOption_ShippingType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Listing_ShippingOption_ShippingType.Descriptor instead.
func (Listing_ShippingOption_ShippingType) EnumDescriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{0, 2, 0}
}

type Listing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Slug               string                    `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	VendorID           *ID                       `protobuf:"bytes,2,opt,name=vendorID,proto3" json:"vendorID,omitempty"`
	Metadata           *Listing_Metadata         `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Item               *Listing_Item             `protobuf:"bytes,4,opt,name=item,proto3" json:"item,omitempty"`
	ShippingOptions    []*Listing_ShippingOption `protobuf:"bytes,5,rep,name=shippingOptions,proto3" json:"shippingOptions,omitempty"`
	Taxes              []*Listing_Tax            `protobuf:"bytes,6,rep,name=taxes,proto3" json:"taxes,omitempty"`
	Coupons            []*Listing_Coupon         `protobuf:"bytes,7,rep,name=coupons,proto3" json:"coupons,omitempty"`
	Moderators         []string                  `protobuf:"bytes,8,rep,name=moderators,proto3" json:"moderators,omitempty"`
	TermsAndConditions string                    `protobuf:"bytes,9,opt,name=termsAndConditions,proto3" json:"termsAndConditions,omitempty"`
	RefundPolicy       string                    `protobuf:"bytes,10,opt,name=refundPolicy,proto3" json:"refundPolicy,omitempty"`
}

func (x *Listing) Reset() {
	*x = Listing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listing_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Listing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Listing) ProtoMessage() {}

func (x *Listing) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Listing.ProtoReflect.Descriptor instead.
func (*Listing) Descriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{0}
}

func (x *Listing) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Listing) GetVendorID() *ID {
	if x != nil {
		return x.VendorID
	}
	return nil
}

func (x *Listing) GetMetadata() *Listing_Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Listing) GetItem() *Listing_Item {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *Listing) GetShippingOptions() []*Listing_ShippingOption {
	if x != nil {
		return x.ShippingOptions
	}
	return nil
}

func (x *Listing) GetTaxes() []*Listing_Tax {
	if x != nil {
		return x.Taxes
	}
	return nil
}

func (x *Listing) GetCoupons() []*Listing_Coupon {
	if x != nil {
		return x.Coupons
	}
	return nil
}

func (x *Listing) GetModerators() []string {
	if x != nil {
		return x.Moderators
	}
	return nil
}

func (x *Listing) GetTermsAndConditions() string {
	if x != nil {
		return x.TermsAndConditions
	}
	return ""
}

func (x *Listing) GetRefundPolicy() string {
	if x != nil {
		return x.RefundPolicy
	}
	return ""
}

type SignedListing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Listing   *Listing `protobuf:"bytes,1,opt,name=listing,proto3" json:"listing,omitempty"`
	Cid       string   `protobuf:"bytes,2,opt,name=cid,proto3" json:"cid,omitempty"`
	Signature []byte   `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *SignedListing) Reset() {
	*x = SignedListing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listing_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignedListing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedListing) ProtoMessage() {}

func (x *SignedListing) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedListing.ProtoReflect.Descriptor instead.
func (*SignedListing) Descriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{1}
}

func (x *SignedListing) GetListing() *Listing {
	if x != nil {
		return x.Listing
	}
	return nil
}

func (x *SignedListing) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *SignedListing) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type Listing_Metadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version            uint32                        `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	ContractType       Listing_Metadata_ContractType `protobuf:"varint,2,opt,name=contractType,proto3,enum=Listing_Metadata_ContractType" json:"contractType,omitempty"`
	Format             Listing_Metadata_Format       `protobuf:"varint,3,opt,name=format,proto3,enum=Listing_Metadata_Format" json:"format,omitempty"`
	Expiry             *timestamp.Timestamp          `protobuf:"bytes,4,opt,name=expiry,proto3" json:"expiry,omitempty"`
	AcceptedCurrencies []string                      `protobuf:"bytes,5,rep,name=acceptedCurrencies,proto3" json:"acceptedCurrencies,omitempty"`
	Language           string                        `protobuf:"bytes,6,opt,name=language,proto3" json:"language,omitempty"`
	EscrowTimeoutHours uint32                        `protobuf:"varint,7,opt,name=escrowTimeoutHours,proto3" json:"escrowTimeoutHours,omitempty"`
	PricingCurrency    *Currency                     `protobuf:"bytes,9,opt,name=pricingCurrency,proto3" json:"pricingCurrency,omitempty"`
}

func (x *Listing_Metadata) Reset() {
	*x = Listing_Metadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listing_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Listing_Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Listing_Metadata) ProtoMessage() {}

func (x *Listing_Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Listing_Metadata.ProtoReflect.Descriptor instead.
func (*Listing_Metadata) Descriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Listing_Metadata) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Listing_Metadata) GetContractType() Listing_Metadata_ContractType {
	if x != nil {
		return x.ContractType
	}
	return Listing_Metadata_PHYSICAL_GOOD
}

func (x *Listing_Metadata) GetFormat() Listing_Metadata_Format {
	if x != nil {
		return x.Format
	}
	return Listing_Metadata_FIXED_PRICE
}

func (x *Listing_Metadata) GetExpiry() *timestamp.Timestamp {
	if x != nil {
		return x.Expiry
	}
	return nil
}

func (x *Listing_Metadata) GetAcceptedCurrencies() []string {
	if x != nil {
		return x.AcceptedCurrencies
	}
	return nil
}

func (x *Listing_Metadata) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Listing_Metadata) GetEscrowTimeoutHours() uint32 {
	if x != nil {
		return x.EscrowTimeoutHours
	}
	return 0
}

func (x *Listing_Metadata) GetPricingCurrency() *Currency {
	if x != nil {
		return x.PricingCurrency
	}
	return nil
}

type Listing_Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title                      string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description                string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ProcessingTime             string                 `protobuf:"bytes,3,opt,name=processingTime,proto3" json:"processingTime,omitempty"`
	Nsfw                       bool                   `protobuf:"varint,4,opt,name=nsfw,proto3" json:"nsfw,omitempty"`
	Tags                       []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Images                     []*Listing_Item_Image  `protobuf:"bytes,6,rep,name=images,proto3" json:"images,omitempty"`
	Categories                 []string               `protobuf:"bytes,7,rep,name=categories,proto3" json:"categories,omitempty"`
	Grams                      float32                `protobuf:"fixed32,8,opt,name=grams,proto3" json:"grams,omitempty"`
	Condition                  string                 `protobuf:"bytes,9,opt,name=condition,proto3" json:"condition,omitempty"`
	Options                    []*Listing_Item_Option `protobuf:"bytes,10,rep,name=options,proto3" json:"options,omitempty"`
	Skus                       []*Listing_Item_Sku    `protobuf:"bytes,11,rep,name=skus,proto3" json:"skus,omitempty"`
	Price                      string                 `protobuf:"bytes,12,opt,name=price,proto3" json:"price,omitempty"`
	CryptoListingCurrencyCode  string                 `protobuf:"bytes,13,opt,name=cryptoListingCurrencyCode,proto3" json:"cryptoListingCurrencyCode,omitempty"`
	CryptoListingPriceModifier float32                `protobuf:"fixed32,14,opt,name=cryptoListingPriceModifier,proto3" json:"cryptoListingPriceModifier,omitempty"`
}

func (x *Listing_Item) Reset() {
	*x = Listing_Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listing_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Listing_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Listing_Item) ProtoMessage() {}

func (x *Listing_Item) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Listing_Item.ProtoReflect.Descriptor instead.
func (*Listing_Item) Descriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Listing_Item) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Listing_Item) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Listing_Item) GetProcessingTime() string {
	if x != nil {
		return x.ProcessingTime
	}
	return ""
}

func (x *Listing_Item) GetNsfw() bool {
	if x != nil {
		return x.Nsfw
	}
	return false
}

func (x *Listing_Item) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Listing_Item) GetImages() []*Listing_Item_Image {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *Listing_Item) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *Listing_Item) GetGrams() float32 {
	if x != nil {
		return x.Grams
	}
	return 0
}

func (x *Listing_Item) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *Listing_Item) GetOptions() []*Listing_Item_Option {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *Listing_Item) GetSkus() []*Listing_Item_Sku {
	if x != nil {
		return x.Skus
	}
	return nil
}

func (x *Listing_Item) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Listing_Item) GetCryptoListingCurrencyCode() string {
	if x != nil {
		return x.CryptoListingCurrencyCode
	}
	return ""
}

func (x *Listing_Item) GetCryptoListingPriceModifier() float32 {
	if x != nil {
		return x.CryptoListingPriceModifier
	}
	return 0
}

type Listing_ShippingOption struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string                              `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type     Listing_ShippingOption_ShippingType `protobuf:"varint,2,opt,name=type,proto3,enum=Listing_ShippingOption_ShippingType" json:"type,omitempty"`
	Regions  []CountryCode                       `protobuf:"varint,3,rep,packed,name=regions,proto3,enum=CountryCode" json:"regions,omitempty"`
	Services []*Listing_ShippingOption_Service   `protobuf:"bytes,4,rep,name=services,proto3" json:"services,omitempty"`
}

func (x *Listing_ShippingOption) Reset() {
	*x = Listing_ShippingOption{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listing_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Listing_ShippingOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Listing_ShippingOption) ProtoMessage() {}

func (x *Listing_ShippingOption) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Listing_ShippingOption.ProtoReflect.Descriptor instead.
func (*Listing_ShippingOption) Descriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Listing_ShippingOption) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Listing_ShippingOption) GetType() Listing_ShippingOption_ShippingType {
	if x != nil {
		return x.Type
	}
	return Listing_ShippingOption_LOCAL_PICKUP
}

func (x *Listing_ShippingOption) GetRegions() []CountryCode {
	if x != nil {
		return x.Regions
	}
	return nil
}

func (x *Listing_ShippingOption) GetServices() []*Listing_ShippingOption_Service {
	if x != nil {
		return x.Services
	}
	return nil
}

type Listing_Tax struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaxType     string        `protobuf:"bytes,1,opt,name=taxType,proto3" json:"taxType,omitempty"`
	TaxRegions  []CountryCode `protobuf:"varint,2,rep,packed,name=taxRegions,proto3,enum=CountryCode" json:"taxRegions,omitempty"`
	TaxShipping bool          `protobuf:"varint,3,opt,name=taxShipping,proto3" json:"taxShipping,omitempty"`
	Percentage  float32       `protobuf:"fixed32,4,opt,name=percentage,proto3" json:"percentage,omitempty"`
}

func (x *Listing_Tax) Reset() {
	*x = Listing_Tax{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listing_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Listing_Tax) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Listing_Tax) ProtoMessage() {}

func (x *Listing_Tax) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Listing_Tax.ProtoReflect.Descriptor instead.
func (*Listing_Tax) Descriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{0, 3}
}

func (x *Listing_Tax) GetTaxType() string {
	if x != nil {
		return x.TaxType
	}
	return ""
}

func (x *Listing_Tax) GetTaxRegions() []CountryCode {
	if x != nil {
		return x.TaxRegions
	}
	return nil
}

func (x *Listing_Tax) GetTaxShipping() bool {
	if x != nil {
		return x.TaxShipping
	}
	return false
}

func (x *Listing_Tax) GetPercentage() float32 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

type Listing_Coupon struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	// Types that are assignable to Code:
	//	*Listing_Coupon_Hash
	//	*Listing_Coupon_DiscountCode
	Code isListing_Coupon_Code `protobuf_oneof:"code"`
	// Types that are assignable to Discount:
	//	*Listing_Coupon_PercentDiscount
	//	*Listing_Coupon_PriceDiscount
	Discount isListing_Coupon_Discount `protobuf_oneof:"discount"`
}

func (x *Listing_Coupon) Reset() {
	*x = Listing_Coupon{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listing_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Listing_Coupon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Listing_Coupon) ProtoMessage() {}

func (x *Listing_Coupon) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Listing_Coupon.ProtoReflect.Descriptor instead.
func (*Listing_Coupon) Descriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{0, 4}
}

func (x *Listing_Coupon) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (m *Listing_Coupon) GetCode() isListing_Coupon_Code {
	if m != nil {
		return m.Code
	}
	return nil
}

func (x *Listing_Coupon) GetHash() string {
	if x, ok := x.GetCode().(*Listing_Coupon_Hash); ok {
		return x.Hash
	}
	return ""
}

func (x *Listing_Coupon) GetDiscountCode() string {
	if x, ok := x.GetCode().(*Listing_Coupon_DiscountCode); ok {
		return x.DiscountCode
	}
	return ""
}

func (m *Listing_Coupon) GetDiscount() isListing_Coupon_Discount {
	if m != nil {
		return m.Discount
	}
	return nil
}

func (x *Listing_Coupon) GetPercentDiscount() float32 {
	if x, ok := x.GetDiscount().(*Listing_Coupon_PercentDiscount); ok {
		return x.PercentDiscount
	}
	return 0
}

func (x *Listing_Coupon) GetPriceDiscount() string {
	if x, ok := x.GetDiscount().(*Listing_Coupon_PriceDiscount); ok {
		return x.PriceDiscount
	}
	return ""
}

type isListing_Coupon_Code interface {
	isListing_Coupon_Code()
}

type Listing_Coupon_Hash struct {
	Hash string `protobuf:"bytes,2,opt,name=hash,proto3,oneof"`
}

type Listing_Coupon_DiscountCode struct {
	DiscountCode string `protobuf:"bytes,3,opt,name=discountCode,proto3,oneof"`
}

func (*Listing_Coupon_Hash) isListing_Coupon_Code() {}

func (*Listing_Coupon_DiscountCode) isListing_Coupon_Code() {}

type isListing_Coupon_Discount interface {
	isListing_Coupon_Discount()
}

type Listing_Coupon_PercentDiscount struct {
	PercentDiscount float32 `protobuf:"fixed32,4,opt,name=percentDiscount,proto3,oneof"`
}

type Listing_Coupon_PriceDiscount struct {
	PriceDiscount string `protobuf:"bytes,5,opt,name=priceDiscount,proto3,oneof"`
}

func (*Listing_Coupon_PercentDiscount) isListing_Coupon_Discount() {}

func (*Listing_Coupon_PriceDiscount) isListing_Coupon_Discount() {}

type Listing_Item_Option struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string                         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string                         `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Variants    []*Listing_Item_Option_Variant `protobuf:"bytes,3,rep,name=variants,proto3" json:"variants,omitempty"`
}

func (x *Listing_Item_Option) Reset() {
	*x = Listing_Item_Option{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listing_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Listing_Item_Option) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Listing_Item_Option) ProtoMessage() {}

func (x *Listing_Item_Option) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Listing_Item_Option.ProtoReflect.Descriptor instead.
func (*Listing_Item_Option) Descriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *Listing_Item_Option) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Listing_Item_Option) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Listing_Item_Option) GetVariants() []*Listing_Item_Option_Variant {
	if x != nil {
		return x.Variants
	}
	return nil
}

type Listing_Item_Sku struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Selections []*Listing_Item_Sku_Selection `protobuf:"bytes,1,rep,name=selections,proto3" json:"selections,omitempty"`
	ProductID  string                        `protobuf:"bytes,2,opt,name=productID,proto3" json:"productID,omitempty"`
	Quantity   string                        `protobuf:"bytes,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Surcharge  string                        `protobuf:"bytes,4,opt,name=surcharge,proto3" json:"surcharge,omitempty"`
}

func (x *Listing_Item_Sku) Reset() {
	*x = Listing_Item_Sku{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listing_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Listing_Item_Sku) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Listing_Item_Sku) ProtoMessage() {}

func (x *Listing_Item_Sku) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Listing_Item_Sku.ProtoReflect.Descriptor instead.
func (*Listing_Item_Sku) Descriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{0, 1, 1}
}

func (x *Listing_Item_Sku) GetSelections() []*Listing_Item_Sku_Selection {
	if x != nil {
		return x.Selections
	}
	return nil
}

func (x *Listing_Item_Sku) GetProductID() string {
	if x != nil {
		return x.ProductID
	}
	return ""
}

func (x *Listing_Item_Sku) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *Listing_Item_Sku) GetSurcharge() string {
	if x != nil {
		return x.Surcharge
	}
	return ""
}

type Listing_Item_Image struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filename string `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Original string `protobuf:"bytes,2,opt,name=original,proto3" json:"original,omitempty"`
	Large    string `protobuf:"bytes,3,opt,name=large,proto3" json:"large,omitempty"`
	Medium   string `protobuf:"bytes,4,opt,name=medium,proto3" json:"medium,omitempty"`
	Small    string `protobuf:"bytes,5,opt,name=small,proto3" json:"small,omitempty"`
	Tiny     string `protobuf:"bytes,6,opt,name=tiny,proto3" json:"tiny,omitempty"`
}

func (x *Listing_Item_Image) Reset() {
	*x = Listing_Item_Image{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listing_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Listing_Item_Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Listing_Item_Image) ProtoMessage() {}

func (x *Listing_Item_Image) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Listing_Item_Image.ProtoReflect.Descriptor instead.
func (*Listing_Item_Image) Descriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{0, 1, 2}
}

func (x *Listing_Item_Image) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Listing_Item_Image) GetOriginal() string {
	if x != nil {
		return x.Original
	}
	return ""
}

func (x *Listing_Item_Image) GetLarge() string {
	if x != nil {
		return x.Large
	}
	return ""
}

func (x *Listing_Item_Image) GetMedium() string {
	if x != nil {
		return x.Medium
	}
	return ""
}

func (x *Listing_Item_Image) GetSmall() string {
	if x != nil {
		return x.Small
	}
	return ""
}

func (x *Listing_Item_Image) GetTiny() string {
	if x != nil {
		return x.Tiny
	}
	return ""
}

type Listing_Item_Option_Variant struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string              `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Image *Listing_Item_Image `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
}

func (x *Listing_Item_Option_Variant) Reset() {
	*x = Listing_Item_Option_Variant{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listing_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Listing_Item_Option_Variant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Listing_Item_Option_Variant) ProtoMessage() {}

func (x *Listing_Item_Option_Variant) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Listing_Item_Option_Variant.ProtoReflect.Descriptor instead.
func (*Listing_Item_Option_Variant) Descriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{0, 1, 0, 0}
}

func (x *Listing_Item_Option_Variant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Listing_Item_Option_Variant) GetImage() *Listing_Item_Image {
	if x != nil {
		return x.Image
	}
	return nil
}

type Listing_Item_Sku_Selection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Option  string `protobuf:"bytes,1,opt,name=option,proto3" json:"option,omitempty"`
	Variant string `protobuf:"bytes,2,opt,name=variant,proto3" json:"variant,omitempty"`
}

func (x *Listing_Item_Sku_Selection) Reset() {
	*x = Listing_Item_Sku_Selection{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listing_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Listing_Item_Sku_Selection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Listing_Item_Sku_Selection) ProtoMessage() {}

func (x *Listing_Item_Sku_Selection) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Listing_Item_Sku_Selection.ProtoReflect.Descriptor instead.
func (*Listing_Item_Sku_Selection) Descriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{0, 1, 1, 0}
}

func (x *Listing_Item_Sku_Selection) GetOption() string {
	if x != nil {
		return x.Option
	}
	return ""
}

func (x *Listing_Item_Sku_Selection) GetVariant() string {
	if x != nil {
		return x.Variant
	}
	return ""
}

type Listing_ShippingOption_Service struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name                string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	EstimatedDelivery   string `protobuf:"bytes,2,opt,name=estimatedDelivery,proto3" json:"estimatedDelivery,omitempty"`
	Price               string `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	AdditionalItemPrice string `protobuf:"bytes,4,opt,name=additionalItemPrice,proto3" json:"additionalItemPrice,omitempty"`
}

func (x *Listing_ShippingOption_Service) Reset() {
	*x = Listing_ShippingOption_Service{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listing_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Listing_ShippingOption_Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Listing_ShippingOption_Service) ProtoMessage() {}

func (x *Listing_ShippingOption_Service) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Listing_ShippingOption_Service.ProtoReflect.Descriptor instead.
func (*Listing_ShippingOption_Service) Descriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{0, 2, 0}
}

func (x *Listing_ShippingOption_Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Listing_ShippingOption_Service) GetEstimatedDelivery() string {
	if x != nil {
		return x.EstimatedDelivery
	}
	return ""
}

func (x *Listing_ShippingOption_Service) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Listing_ShippingOption_Service) GetAdditionalItemPrice() string {
	if x != nil {
		return x.AdditionalItemPrice
	}
	return ""
}

var File_listing_proto protoreflect.FileDescriptor

var file_listing_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x12, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xc9, 0x15, 0x0a, 0x07, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x12,
	0x0a, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x6c,
	0x75, 0x67, 0x12, 0x1f, 0x0a, 0x08, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x49, 0x44, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x03, 0x2e, 0x49, 0x44, 0x52, 0x08, 0x76, 0x65, 0x6e, 0x64, 0x6f,
	0x72, 0x49, 0x44, 0x12, 0x2d, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2e,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x21, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52,
	0x04, 0x69, 0x74, 0x65, 0x6d, 0x12, 0x41, 0x0a, 0x0f, 0x73, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e,
	0x67, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x53, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e,
	0x67, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0f, 0x73, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e,
	0x67, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x22, 0x0a, 0x05, 0x74, 0x61, 0x78, 0x65,
	0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e,
	0x67, 0x2e, 0x54, 0x61, 0x78, 0x52, 0x05, 0x74, 0x61, 0x78, 0x65, 0x73, 0x12, 0x29, 0x0a, 0x07,
	0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x52, 0x07,
	0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x6f, 0x64, 0x65, 0x72,
	0x61, 0x74, 0x6f, 0x72, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x6f, 0x64,
	0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x12, 0x2e, 0x0a, 0x12, 0x74, 0x65, 0x72, 0x6d, 0x73,
	0x41, 0x6e, 0x64, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x12, 0x74, 0x65, 0x72, 0x6d, 0x73, 0x41, 0x6e, 0x64, 0x43, 0x6f, 0x6e,
	0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x65, 0x66, 0x75, 0x6e,
	0x64, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72,
	0x65, 0x66, 0x75, 0x6e, 0x64, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x1a, 0x92, 0x04, 0x0a, 0x08,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x42, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x69,
	0x6e, 0x67, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x43, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x30, 0x0a, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67,
	0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74,
	0x52, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x32, 0x0a, 0x06, 0x65, 0x78, 0x70, 0x69,
	0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x06, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x12, 0x2e, 0x0a, 0x12,
	0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x69,
	0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x12, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74,
	0x65, 0x64, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08,
	0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x12, 0x2e, 0x0a, 0x12, 0x65, 0x73, 0x63, 0x72,
	0x6f, 0x77, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x12, 0x65, 0x73, 0x63, 0x72, 0x6f, 0x77, 0x54, 0x69, 0x6d, 0x65,
	0x6f, 0x75, 0x74, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x12, 0x33, 0x0a, 0x0f, 0x70, 0x72, 0x69, 0x63,
	0x69, 0x6e, 0x67, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x09, 0x2e, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x0f, 0x70, 0x72,
	0x69, 0x63, 0x69, 0x6e, 0x67, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x22, 0x64, 0x0a,
	0x0c, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x11, 0x0a,
	0x0d, 0x50, 0x48, 0x59, 0x53, 0x49, 0x43, 0x41, 0x4c, 0x5f, 0x47, 0x4f, 0x4f, 0x44, 0x10, 0x00,
	0x12, 0x10, 0x0a, 0x0c, 0x44, 0x49, 0x47, 0x49, 0x54, 0x41, 0x4c, 0x5f, 0x47, 0x4f, 0x4f, 0x44,
	0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x45, 0x52, 0x56, 0x49, 0x43, 0x45, 0x10, 0x02, 0x12,
	0x0e, 0x0a, 0x0a, 0x43, 0x4c, 0x41, 0x53, 0x53, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x03, 0x12,
	0x12, 0x0a, 0x0e, 0x43, 0x52, 0x59, 0x50, 0x54, 0x4f, 0x43, 0x55, 0x52, 0x52, 0x45, 0x4e, 0x43,
	0x59, 0x10, 0x04, 0x22, 0x2b, 0x0a, 0x06, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x0f, 0x0a,
	0x0b, 0x46, 0x49, 0x58, 0x45, 0x44, 0x5f, 0x50, 0x52, 0x49, 0x43, 0x45, 0x10, 0x00, 0x12, 0x10,
	0x0a, 0x0c, 0x4d, 0x41, 0x52, 0x4b, 0x45, 0x54, 0x5f, 0x50, 0x52, 0x49, 0x43, 0x45, 0x10, 0x01,
	0x1a, 0xb5, 0x08, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x26, 0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x54,
	0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x70, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x73, 0x66,
	0x77, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x6e, 0x73, 0x66, 0x77, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67,
	0x73, 0x12, 0x2b, 0x0a, 0x06, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x49, 0x74, 0x65, 0x6d,
	0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x06, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x12, 0x1e,
	0x0a, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x18, 0x07, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x67, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x67,
	0x72, 0x61, 0x6d, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x2e, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x0a, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x49, 0x74,
	0x65, 0x6d, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x12, 0x25, 0x0a, 0x04, 0x73, 0x6b, 0x75, 0x73, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x2e,
	0x53, 0x6b, 0x75, 0x52, 0x04, 0x73, 0x6b, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12,
	0x3c, 0x0a, 0x19, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67,
	0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x0d, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x19, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e,
	0x67, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x3e, 0x0a,
	0x1a, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x50, 0x72,
	0x69, 0x63, 0x65, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x72, 0x18, 0x0e, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x1a, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67,
	0x50, 0x72, 0x69, 0x63, 0x65, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x72, 0x1a, 0xc2, 0x01,
	0x0a, 0x06, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x38,
	0x0a, 0x08, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x2e,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x56, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x52, 0x08,
	0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x73, 0x1a, 0x48, 0x0a, 0x07, 0x56, 0x61, 0x72, 0x69,
	0x61, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x29, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67,
	0x2e, 0x49, 0x74, 0x65, 0x6d, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x05, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x1a, 0xd9, 0x01, 0x0a, 0x03, 0x53, 0x6b, 0x75, 0x12, 0x3b, 0x0a, 0x0a, 0x73, 0x65,
	0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x2e, 0x53, 0x6b,
	0x75, 0x2e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x73, 0x65, 0x6c,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x75, 0x72, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x75, 0x72, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x1a,
	0x3d, 0x0a, 0x09, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06,
	0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x1a, 0x97,
	0x01, 0x0a, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c,
	0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x72, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x6c, 0x61, 0x72, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x64, 0x69, 0x75, 0x6d,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x64, 0x69, 0x75, 0x6d, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x6d, 0x61, 0x6c, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73,
	0x6d, 0x61, 0x6c, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6e, 0x79, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x6e, 0x79, 0x1a, 0x8c, 0x03, 0x0a, 0x0e, 0x53, 0x68, 0x69,
	0x70, 0x70, 0x69, 0x6e, 0x67, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x38, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x24, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x53, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x26, 0x0a, 0x07, 0x72, 0x65, 0x67,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x07, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x3b, 0x0a, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x53, 0x68,
	0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x1a, 0x93,
	0x01, 0x0a, 0x07, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2c,
	0x0a, 0x11, 0x65, 0x73, 0x74, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x64, 0x44, 0x65, 0x6c, 0x69, 0x76,
	0x65, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x65, 0x73, 0x74, 0x69, 0x6d,
	0x61, 0x74, 0x65, 0x64, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x12, 0x30, 0x0a, 0x13, 0x61, 0x64, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c,
	0x49, 0x74, 0x65, 0x6d, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x13, 0x61, 0x64, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x22, 0x31, 0x0a, 0x0c, 0x53, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x0c, 0x4c, 0x4f, 0x43, 0x41, 0x4c, 0x5f, 0x50, 0x49,
	0x43, 0x4b, 0x55, 0x50, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x46, 0x49, 0x58, 0x45, 0x44, 0x5f,
	0x50, 0x52, 0x49, 0x43, 0x45, 0x10, 0x01, 0x1a, 0x8f, 0x01, 0x0a, 0x03, 0x54, 0x61, 0x78, 0x12,
	0x18, 0x0a, 0x07, 0x74, 0x61, 0x78, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x74, 0x61, 0x78, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2c, 0x0a, 0x0a, 0x74, 0x61, 0x78,
	0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x0c, 0x2e,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x0a, 0x74, 0x61, 0x78,
	0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x61, 0x78, 0x53, 0x68,
	0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x74, 0x61,
	0x78, 0x53, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x65, 0x72,
	0x63, 0x65, 0x6e, 0x74, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a, 0x70,
	0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x61, 0x67, 0x65, 0x1a, 0xc2, 0x01, 0x0a, 0x06, 0x43, 0x6f,
	0x75, 0x70, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x04, 0x68, 0x61,
	0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68,
	0x12, 0x24, 0x0a, 0x0c, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x6f, 0x64, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0c, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x2a, 0x0a, 0x0f, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e,
	0x74, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x48,
	0x01, 0x52, 0x0f, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x26, 0x0a, 0x0d, 0x70, 0x72, 0x69, 0x63, 0x65, 0x44, 0x69, 0x73, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x0d, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x06, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x42, 0x0a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x63,
	0x0a, 0x0d, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x12,
	0x22, 0x0a, 0x07, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x08, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x07, 0x6c, 0x69, 0x73, 0x74,
	0x69, 0x6e, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x63, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_listing_proto_rawDescOnce sync.Once
	file_listing_proto_rawDescData = file_listing_proto_rawDesc
)

func file_listing_proto_rawDescGZIP() []byte {
	file_listing_proto_rawDescOnce.Do(func() {
		file_listing_proto_rawDescData = protoimpl.X.CompressGZIP(file_listing_proto_rawDescData)
	})
	return file_listing_proto_rawDescData
}

var file_listing_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_listing_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_listing_proto_goTypes = []interface{}{
	(Listing_Metadata_ContractType)(0),       // 0: Listing.Metadata.ContractType
	(Listing_Metadata_Format)(0),             // 1: Listing.Metadata.Format
	(Listing_ShippingOption_ShippingType)(0), // 2: Listing.ShippingOption.ShippingType
	(*Listing)(nil),                          // 3: Listing
	(*SignedListing)(nil),                    // 4: SignedListing
	(*Listing_Metadata)(nil),                 // 5: Listing.Metadata
	(*Listing_Item)(nil),                     // 6: Listing.Item
	(*Listing_ShippingOption)(nil),           // 7: Listing.ShippingOption
	(*Listing_Tax)(nil),                      // 8: Listing.Tax
	(*Listing_Coupon)(nil),                   // 9: Listing.Coupon
	(*Listing_Item_Option)(nil),              // 10: Listing.Item.Option
	(*Listing_Item_Sku)(nil),                 // 11: Listing.Item.Sku
	(*Listing_Item_Image)(nil),               // 12: Listing.Item.Image
	(*Listing_Item_Option_Variant)(nil),      // 13: Listing.Item.Option.Variant
	(*Listing_Item_Sku_Selection)(nil),       // 14: Listing.Item.Sku.Selection
	(*Listing_ShippingOption_Service)(nil),   // 15: Listing.ShippingOption.Service
	(*ID)(nil),                               // 16: ID
	(*timestamp.Timestamp)(nil),              // 17: google.protobuf.Timestamp
	(*Currency)(nil),                         // 18: Currency
	(CountryCode)(0),                         // 19: CountryCode
}
var file_listing_proto_depIdxs = []int32{
	16, // 0: Listing.vendorID:type_name -> ID
	5,  // 1: Listing.metadata:type_name -> Listing.Metadata
	6,  // 2: Listing.item:type_name -> Listing.Item
	7,  // 3: Listing.shippingOptions:type_name -> Listing.ShippingOption
	8,  // 4: Listing.taxes:type_name -> Listing.Tax
	9,  // 5: Listing.coupons:type_name -> Listing.Coupon
	3,  // 6: SignedListing.listing:type_name -> Listing
	0,  // 7: Listing.Metadata.contractType:type_name -> Listing.Metadata.ContractType
	1,  // 8: Listing.Metadata.format:type_name -> Listing.Metadata.Format
	17, // 9: Listing.Metadata.expiry:type_name -> google.protobuf.Timestamp
	18, // 10: Listing.Metadata.pricingCurrency:type_name -> Currency
	12, // 11: Listing.Item.images:type_name -> Listing.Item.Image
	10, // 12: Listing.Item.options:type_name -> Listing.Item.Option
	11, // 13: Listing.Item.skus:type_name -> Listing.Item.Sku
	2,  // 14: Listing.ShippingOption.type:type_name -> Listing.ShippingOption.ShippingType
	19, // 15: Listing.ShippingOption.regions:type_name -> CountryCode
	15, // 16: Listing.ShippingOption.services:type_name -> Listing.ShippingOption.Service
	19, // 17: Listing.Tax.taxRegions:type_name -> CountryCode
	13, // 18: Listing.Item.Option.variants:type_name -> Listing.Item.Option.Variant
	14, // 19: Listing.Item.Sku.selections:type_name -> Listing.Item.Sku.Selection
	12, // 20: Listing.Item.Option.Variant.image:type_name -> Listing.Item.Image
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_listing_proto_init() }
func file_listing_proto_init() {
	if File_listing_proto != nil {
		return
	}
	file_countrycodes_proto_init()
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_listing_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Listing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listing_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignedListing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listing_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Listing_Metadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listing_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Listing_Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listing_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Listing_ShippingOption); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listing_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Listing_Tax); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listing_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Listing_Coupon); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listing_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Listing_Item_Option); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listing_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Listing_Item_Sku); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listing_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Listing_Item_Image); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listing_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Listing_Item_Option_Variant); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listing_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Listing_Item_Sku_Selection); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listing_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Listing_ShippingOption_Service); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_listing_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*Listing_Coupon_Hash)(nil),
		(*Listing_Coupon_DiscountCode)(nil),
		(*Listing_Coupon_PercentDiscount)(nil),
		(*Listing_Coupon_PriceDiscount)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_listing_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_listing_proto_goTypes,
		DependencyIndexes: file_listing_proto_depIdxs,
		EnumInfos:         file_listing_proto_enumTypes,
		MessageInfos:      file_listing_proto_msgTypes,
	}.Build()
	File_listing_proto = out.File
	file_listing_proto_rawDesc = nil
	file_listing_proto_goTypes = nil
	file_listing_proto_depIdxs = nil
}
