// Code generated by protoc-gen-go. DO NOT EDIT.
// source: orders.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OrderOpen_Payment_Method int32

const (
	OrderOpen_Payment_DIRECT     OrderOpen_Payment_Method = 0
	OrderOpen_Payment_CANCELABLE OrderOpen_Payment_Method = 1
	OrderOpen_Payment_MODERATED  OrderOpen_Payment_Method = 2
)

var OrderOpen_Payment_Method_name = map[int32]string{
	0: "DIRECT",
	1: "CANCELABLE",
	2: "MODERATED",
}

var OrderOpen_Payment_Method_value = map[string]int32{
	"DIRECT":     0,
	"CANCELABLE": 1,
	"MODERATED":  2,
}

func (x OrderOpen_Payment_Method) String() string {
	return proto.EnumName(OrderOpen_Payment_Method_name, int32(x))
}

func (OrderOpen_Payment_Method) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e0f5d4cf0fc9e41b, []int{0, 2, 0}
}

type OrderReject_RejectType int32

const (
	OrderReject_USER_REJECT      OrderReject_RejectType = 0
	OrderReject_VALIDATION_ERROR OrderReject_RejectType = 1
)

var OrderReject_RejectType_name = map[int32]string{
	0: "USER_REJECT",
	1: "VALIDATION_ERROR",
}

var OrderReject_RejectType_value = map[string]int32{
	"USER_REJECT":      0,
	"VALIDATION_ERROR": 1,
}

func (x OrderReject_RejectType) String() string {
	return proto.EnumName(OrderReject_RejectType_name, int32(x))
}

func (OrderReject_RejectType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e0f5d4cf0fc9e41b, []int{1, 0}
}

type OrderOpen struct {
	Listings             []*SignedListing     `protobuf:"bytes,1,rep,name=listings,proto3" json:"listings,omitempty"`
	RefundAddress        string               `protobuf:"bytes,2,opt,name=refundAddress,proto3" json:"refundAddress,omitempty"`
	Shipping             *OrderOpen_Shipping  `protobuf:"bytes,3,opt,name=shipping,proto3" json:"shipping,omitempty"`
	BuyerID              *ID                  `protobuf:"bytes,4,opt,name=buyerID,proto3" json:"buyerID,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Items                []*OrderOpen_Item    `protobuf:"bytes,6,rep,name=items,proto3" json:"items,omitempty"`
	Payment              *OrderOpen_Payment   `protobuf:"bytes,7,opt,name=payment,proto3" json:"payment,omitempty"`
	RatingKeys           [][]byte             `protobuf:"bytes,8,rep,name=ratingKeys,proto3" json:"ratingKeys,omitempty"`
	AlternateContactInfo string               `protobuf:"bytes,9,opt,name=alternateContactInfo,proto3" json:"alternateContactInfo,omitempty"`
	MessageSignature     []byte               `protobuf:"bytes,10,opt,name=messageSignature,proto3" json:"messageSignature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *OrderOpen) Reset()         { *m = OrderOpen{} }
func (m *OrderOpen) String() string { return proto.CompactTextString(m) }
func (*OrderOpen) ProtoMessage()    {}
func (*OrderOpen) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f5d4cf0fc9e41b, []int{0}
}

func (m *OrderOpen) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderOpen.Unmarshal(m, b)
}
func (m *OrderOpen) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderOpen.Marshal(b, m, deterministic)
}
func (m *OrderOpen) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderOpen.Merge(m, src)
}
func (m *OrderOpen) XXX_Size() int {
	return xxx_messageInfo_OrderOpen.Size(m)
}
func (m *OrderOpen) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderOpen.DiscardUnknown(m)
}

var xxx_messageInfo_OrderOpen proto.InternalMessageInfo

func (m *OrderOpen) GetListings() []*SignedListing {
	if m != nil {
		return m.Listings
	}
	return nil
}

func (m *OrderOpen) GetRefundAddress() string {
	if m != nil {
		return m.RefundAddress
	}
	return ""
}

func (m *OrderOpen) GetShipping() *OrderOpen_Shipping {
	if m != nil {
		return m.Shipping
	}
	return nil
}

func (m *OrderOpen) GetBuyerID() *ID {
	if m != nil {
		return m.BuyerID
	}
	return nil
}

func (m *OrderOpen) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *OrderOpen) GetItems() []*OrderOpen_Item {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *OrderOpen) GetPayment() *OrderOpen_Payment {
	if m != nil {
		return m.Payment
	}
	return nil
}

func (m *OrderOpen) GetRatingKeys() [][]byte {
	if m != nil {
		return m.RatingKeys
	}
	return nil
}

func (m *OrderOpen) GetAlternateContactInfo() string {
	if m != nil {
		return m.AlternateContactInfo
	}
	return ""
}

func (m *OrderOpen) GetMessageSignature() []byte {
	if m != nil {
		return m.MessageSignature
	}
	return nil
}

type OrderOpen_Shipping struct {
	ShipTo               string      `protobuf:"bytes,1,opt,name=shipTo,proto3" json:"shipTo,omitempty"`
	Address              string      `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	City                 string      `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	State                string      `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	PostalCode           string      `protobuf:"bytes,5,opt,name=postalCode,proto3" json:"postalCode,omitempty"`
	Country              CountryCode `protobuf:"varint,6,opt,name=country,proto3,enum=CountryCode" json:"country,omitempty"`
	AddressNotes         string      `protobuf:"bytes,7,opt,name=addressNotes,proto3" json:"addressNotes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *OrderOpen_Shipping) Reset()         { *m = OrderOpen_Shipping{} }
func (m *OrderOpen_Shipping) String() string { return proto.CompactTextString(m) }
func (*OrderOpen_Shipping) ProtoMessage()    {}
func (*OrderOpen_Shipping) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f5d4cf0fc9e41b, []int{0, 0}
}

func (m *OrderOpen_Shipping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderOpen_Shipping.Unmarshal(m, b)
}
func (m *OrderOpen_Shipping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderOpen_Shipping.Marshal(b, m, deterministic)
}
func (m *OrderOpen_Shipping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderOpen_Shipping.Merge(m, src)
}
func (m *OrderOpen_Shipping) XXX_Size() int {
	return xxx_messageInfo_OrderOpen_Shipping.Size(m)
}
func (m *OrderOpen_Shipping) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderOpen_Shipping.DiscardUnknown(m)
}

var xxx_messageInfo_OrderOpen_Shipping proto.InternalMessageInfo

func (m *OrderOpen_Shipping) GetShipTo() string {
	if m != nil {
		return m.ShipTo
	}
	return ""
}

func (m *OrderOpen_Shipping) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *OrderOpen_Shipping) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *OrderOpen_Shipping) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *OrderOpen_Shipping) GetPostalCode() string {
	if m != nil {
		return m.PostalCode
	}
	return ""
}

func (m *OrderOpen_Shipping) GetCountry() CountryCode {
	if m != nil {
		return m.Country
	}
	return CountryCode_NA
}

func (m *OrderOpen_Shipping) GetAddressNotes() string {
	if m != nil {
		return m.AddressNotes
	}
	return ""
}

type OrderOpen_Item struct {
	ListingHash          string                         `protobuf:"bytes,1,opt,name=listingHash,proto3" json:"listingHash,omitempty"`
	Quantity             string                         `protobuf:"bytes,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Options              []*OrderOpen_Item_Option       `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty"`
	ShippingOption       *OrderOpen_Item_ShippingOption `protobuf:"bytes,4,opt,name=shippingOption,proto3" json:"shippingOption,omitempty"`
	Memo                 string                         `protobuf:"bytes,5,opt,name=memo,proto3" json:"memo,omitempty"`
	CouponCodes          []string                       `protobuf:"bytes,6,rep,name=couponCodes,proto3" json:"couponCodes,omitempty"`
	PaymentAddress       string                         `protobuf:"bytes,7,opt,name=paymentAddress,proto3" json:"paymentAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *OrderOpen_Item) Reset()         { *m = OrderOpen_Item{} }
func (m *OrderOpen_Item) String() string { return proto.CompactTextString(m) }
func (*OrderOpen_Item) ProtoMessage()    {}
func (*OrderOpen_Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f5d4cf0fc9e41b, []int{0, 1}
}

func (m *OrderOpen_Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderOpen_Item.Unmarshal(m, b)
}
func (m *OrderOpen_Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderOpen_Item.Marshal(b, m, deterministic)
}
func (m *OrderOpen_Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderOpen_Item.Merge(m, src)
}
func (m *OrderOpen_Item) XXX_Size() int {
	return xxx_messageInfo_OrderOpen_Item.Size(m)
}
func (m *OrderOpen_Item) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderOpen_Item.DiscardUnknown(m)
}

var xxx_messageInfo_OrderOpen_Item proto.InternalMessageInfo

func (m *OrderOpen_Item) GetListingHash() string {
	if m != nil {
		return m.ListingHash
	}
	return ""
}

func (m *OrderOpen_Item) GetQuantity() string {
	if m != nil {
		return m.Quantity
	}
	return ""
}

func (m *OrderOpen_Item) GetOptions() []*OrderOpen_Item_Option {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *OrderOpen_Item) GetShippingOption() *OrderOpen_Item_ShippingOption {
	if m != nil {
		return m.ShippingOption
	}
	return nil
}

func (m *OrderOpen_Item) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func (m *OrderOpen_Item) GetCouponCodes() []string {
	if m != nil {
		return m.CouponCodes
	}
	return nil
}

func (m *OrderOpen_Item) GetPaymentAddress() string {
	if m != nil {
		return m.PaymentAddress
	}
	return ""
}

type OrderOpen_Item_Option struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderOpen_Item_Option) Reset()         { *m = OrderOpen_Item_Option{} }
func (m *OrderOpen_Item_Option) String() string { return proto.CompactTextString(m) }
func (*OrderOpen_Item_Option) ProtoMessage()    {}
func (*OrderOpen_Item_Option) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f5d4cf0fc9e41b, []int{0, 1, 0}
}

func (m *OrderOpen_Item_Option) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderOpen_Item_Option.Unmarshal(m, b)
}
func (m *OrderOpen_Item_Option) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderOpen_Item_Option.Marshal(b, m, deterministic)
}
func (m *OrderOpen_Item_Option) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderOpen_Item_Option.Merge(m, src)
}
func (m *OrderOpen_Item_Option) XXX_Size() int {
	return xxx_messageInfo_OrderOpen_Item_Option.Size(m)
}
func (m *OrderOpen_Item_Option) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderOpen_Item_Option.DiscardUnknown(m)
}

var xxx_messageInfo_OrderOpen_Item_Option proto.InternalMessageInfo

func (m *OrderOpen_Item_Option) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OrderOpen_Item_Option) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type OrderOpen_Item_ShippingOption struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Service              string   `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderOpen_Item_ShippingOption) Reset()         { *m = OrderOpen_Item_ShippingOption{} }
func (m *OrderOpen_Item_ShippingOption) String() string { return proto.CompactTextString(m) }
func (*OrderOpen_Item_ShippingOption) ProtoMessage()    {}
func (*OrderOpen_Item_ShippingOption) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f5d4cf0fc9e41b, []int{0, 1, 1}
}

func (m *OrderOpen_Item_ShippingOption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderOpen_Item_ShippingOption.Unmarshal(m, b)
}
func (m *OrderOpen_Item_ShippingOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderOpen_Item_ShippingOption.Marshal(b, m, deterministic)
}
func (m *OrderOpen_Item_ShippingOption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderOpen_Item_ShippingOption.Merge(m, src)
}
func (m *OrderOpen_Item_ShippingOption) XXX_Size() int {
	return xxx_messageInfo_OrderOpen_Item_ShippingOption.Size(m)
}
func (m *OrderOpen_Item_ShippingOption) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderOpen_Item_ShippingOption.DiscardUnknown(m)
}

var xxx_messageInfo_OrderOpen_Item_ShippingOption proto.InternalMessageInfo

func (m *OrderOpen_Item_ShippingOption) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OrderOpen_Item_ShippingOption) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

type OrderOpen_Payment struct {
	Method               OrderOpen_Payment_Method `protobuf:"varint,1,opt,name=method,proto3,enum=OrderOpen_Payment_Method" json:"method,omitempty"`
	Moderator            string                   `protobuf:"bytes,2,opt,name=moderator,proto3" json:"moderator,omitempty"`
	Amount               string                   `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Chaincode            string                   `protobuf:"bytes,4,opt,name=chaincode,proto3" json:"chaincode,omitempty"`
	Address              string                   `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Script               string                   `protobuf:"bytes,6,opt,name=script,proto3" json:"script,omitempty"`
	ModeratorKey         []byte                   `protobuf:"bytes,7,opt,name=moderatorKey,proto3" json:"moderatorKey,omitempty"`
	Coin                 string                   `protobuf:"bytes,8,opt,name=coin,proto3" json:"coin,omitempty"`
	EscrowReleaseFee     string                   `protobuf:"bytes,9,opt,name=escrowReleaseFee,proto3" json:"escrowReleaseFee,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *OrderOpen_Payment) Reset()         { *m = OrderOpen_Payment{} }
func (m *OrderOpen_Payment) String() string { return proto.CompactTextString(m) }
func (*OrderOpen_Payment) ProtoMessage()    {}
func (*OrderOpen_Payment) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f5d4cf0fc9e41b, []int{0, 2}
}

func (m *OrderOpen_Payment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderOpen_Payment.Unmarshal(m, b)
}
func (m *OrderOpen_Payment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderOpen_Payment.Marshal(b, m, deterministic)
}
func (m *OrderOpen_Payment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderOpen_Payment.Merge(m, src)
}
func (m *OrderOpen_Payment) XXX_Size() int {
	return xxx_messageInfo_OrderOpen_Payment.Size(m)
}
func (m *OrderOpen_Payment) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderOpen_Payment.DiscardUnknown(m)
}

var xxx_messageInfo_OrderOpen_Payment proto.InternalMessageInfo

func (m *OrderOpen_Payment) GetMethod() OrderOpen_Payment_Method {
	if m != nil {
		return m.Method
	}
	return OrderOpen_Payment_DIRECT
}

func (m *OrderOpen_Payment) GetModerator() string {
	if m != nil {
		return m.Moderator
	}
	return ""
}

func (m *OrderOpen_Payment) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *OrderOpen_Payment) GetChaincode() string {
	if m != nil {
		return m.Chaincode
	}
	return ""
}

func (m *OrderOpen_Payment) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *OrderOpen_Payment) GetScript() string {
	if m != nil {
		return m.Script
	}
	return ""
}

func (m *OrderOpen_Payment) GetModeratorKey() []byte {
	if m != nil {
		return m.ModeratorKey
	}
	return nil
}

func (m *OrderOpen_Payment) GetCoin() string {
	if m != nil {
		return m.Coin
	}
	return ""
}

func (m *OrderOpen_Payment) GetEscrowReleaseFee() string {
	if m != nil {
		return m.EscrowReleaseFee
	}
	return ""
}

type OrderReject struct {
	Type                 OrderReject_RejectType `protobuf:"varint,1,opt,name=type,proto3,enum=OrderReject_RejectType" json:"type,omitempty"`
	Reason               string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	MessageSignature     []byte                 `protobuf:"bytes,3,opt,name=messageSignature,proto3" json:"messageSignature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *OrderReject) Reset()         { *m = OrderReject{} }
func (m *OrderReject) String() string { return proto.CompactTextString(m) }
func (*OrderReject) ProtoMessage()    {}
func (*OrderReject) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f5d4cf0fc9e41b, []int{1}
}

func (m *OrderReject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderReject.Unmarshal(m, b)
}
func (m *OrderReject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderReject.Marshal(b, m, deterministic)
}
func (m *OrderReject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderReject.Merge(m, src)
}
func (m *OrderReject) XXX_Size() int {
	return xxx_messageInfo_OrderReject.Size(m)
}
func (m *OrderReject) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderReject.DiscardUnknown(m)
}

var xxx_messageInfo_OrderReject proto.InternalMessageInfo

func (m *OrderReject) GetType() OrderReject_RejectType {
	if m != nil {
		return m.Type
	}
	return OrderReject_USER_REJECT
}

func (m *OrderReject) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *OrderReject) GetMessageSignature() []byte {
	if m != nil {
		return m.MessageSignature
	}
	return nil
}

type OrderConfirmation struct {
	TransactionID        string   `protobuf:"bytes,1,opt,name=transactionID,proto3" json:"transactionID,omitempty"`
	MessageSignature     []byte   `protobuf:"bytes,2,opt,name=messageSignature,proto3" json:"messageSignature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderConfirmation) Reset()         { *m = OrderConfirmation{} }
func (m *OrderConfirmation) String() string { return proto.CompactTextString(m) }
func (*OrderConfirmation) ProtoMessage()    {}
func (*OrderConfirmation) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f5d4cf0fc9e41b, []int{2}
}

func (m *OrderConfirmation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderConfirmation.Unmarshal(m, b)
}
func (m *OrderConfirmation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderConfirmation.Marshal(b, m, deterministic)
}
func (m *OrderConfirmation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderConfirmation.Merge(m, src)
}
func (m *OrderConfirmation) XXX_Size() int {
	return xxx_messageInfo_OrderConfirmation.Size(m)
}
func (m *OrderConfirmation) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderConfirmation.DiscardUnknown(m)
}

var xxx_messageInfo_OrderConfirmation proto.InternalMessageInfo

func (m *OrderConfirmation) GetTransactionID() string {
	if m != nil {
		return m.TransactionID
	}
	return ""
}

func (m *OrderConfirmation) GetMessageSignature() []byte {
	if m != nil {
		return m.MessageSignature
	}
	return nil
}

type OrderCancel struct {
	TransactionID        string   `protobuf:"bytes,1,opt,name=transactionID,proto3" json:"transactionID,omitempty"`
	MessageSignature     []byte   `protobuf:"bytes,2,opt,name=messageSignature,proto3" json:"messageSignature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderCancel) Reset()         { *m = OrderCancel{} }
func (m *OrderCancel) String() string { return proto.CompactTextString(m) }
func (*OrderCancel) ProtoMessage()    {}
func (*OrderCancel) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f5d4cf0fc9e41b, []int{3}
}

func (m *OrderCancel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderCancel.Unmarshal(m, b)
}
func (m *OrderCancel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderCancel.Marshal(b, m, deterministic)
}
func (m *OrderCancel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderCancel.Merge(m, src)
}
func (m *OrderCancel) XXX_Size() int {
	return xxx_messageInfo_OrderCancel.Size(m)
}
func (m *OrderCancel) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderCancel.DiscardUnknown(m)
}

var xxx_messageInfo_OrderCancel proto.InternalMessageInfo

func (m *OrderCancel) GetTransactionID() string {
	if m != nil {
		return m.TransactionID
	}
	return ""
}

func (m *OrderCancel) GetMessageSignature() []byte {
	if m != nil {
		return m.MessageSignature
	}
	return nil
}

type RatingSignatures struct {
	Sigs                 []*RatingSignatures_RatingSignature `protobuf:"bytes,1,rep,name=sigs,proto3" json:"sigs,omitempty"`
	MessageSignature     []byte                              `protobuf:"bytes,2,opt,name=messageSignature,proto3" json:"messageSignature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *RatingSignatures) Reset()         { *m = RatingSignatures{} }
func (m *RatingSignatures) String() string { return proto.CompactTextString(m) }
func (*RatingSignatures) ProtoMessage()    {}
func (*RatingSignatures) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f5d4cf0fc9e41b, []int{4}
}

func (m *RatingSignatures) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RatingSignatures.Unmarshal(m, b)
}
func (m *RatingSignatures) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RatingSignatures.Marshal(b, m, deterministic)
}
func (m *RatingSignatures) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RatingSignatures.Merge(m, src)
}
func (m *RatingSignatures) XXX_Size() int {
	return xxx_messageInfo_RatingSignatures.Size(m)
}
func (m *RatingSignatures) XXX_DiscardUnknown() {
	xxx_messageInfo_RatingSignatures.DiscardUnknown(m)
}

var xxx_messageInfo_RatingSignatures proto.InternalMessageInfo

func (m *RatingSignatures) GetSigs() []*RatingSignatures_RatingSignature {
	if m != nil {
		return m.Sigs
	}
	return nil
}

func (m *RatingSignatures) GetMessageSignature() []byte {
	if m != nil {
		return m.MessageSignature
	}
	return nil
}

type RatingSignatures_RatingSignature struct {
	Slug                 string   `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	RatingKey            []byte   `protobuf:"bytes,2,opt,name=ratingKey,proto3" json:"ratingKey,omitempty"`
	VendorSignature      []byte   `protobuf:"bytes,3,opt,name=vendorSignature,proto3" json:"vendorSignature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RatingSignatures_RatingSignature) Reset()         { *m = RatingSignatures_RatingSignature{} }
func (m *RatingSignatures_RatingSignature) String() string { return proto.CompactTextString(m) }
func (*RatingSignatures_RatingSignature) ProtoMessage()    {}
func (*RatingSignatures_RatingSignature) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f5d4cf0fc9e41b, []int{4, 0}
}

func (m *RatingSignatures_RatingSignature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RatingSignatures_RatingSignature.Unmarshal(m, b)
}
func (m *RatingSignatures_RatingSignature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RatingSignatures_RatingSignature.Marshal(b, m, deterministic)
}
func (m *RatingSignatures_RatingSignature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RatingSignatures_RatingSignature.Merge(m, src)
}
func (m *RatingSignatures_RatingSignature) XXX_Size() int {
	return xxx_messageInfo_RatingSignatures_RatingSignature.Size(m)
}
func (m *RatingSignatures_RatingSignature) XXX_DiscardUnknown() {
	xxx_messageInfo_RatingSignatures_RatingSignature.DiscardUnknown(m)
}

var xxx_messageInfo_RatingSignatures_RatingSignature proto.InternalMessageInfo

func (m *RatingSignatures_RatingSignature) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *RatingSignatures_RatingSignature) GetRatingKey() []byte {
	if m != nil {
		return m.RatingKey
	}
	return nil
}

func (m *RatingSignatures_RatingSignature) GetVendorSignature() []byte {
	if m != nil {
		return m.VendorSignature
	}
	return nil
}

type OrderFulfillment struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderFulfillment) Reset()         { *m = OrderFulfillment{} }
func (m *OrderFulfillment) String() string { return proto.CompactTextString(m) }
func (*OrderFulfillment) ProtoMessage()    {}
func (*OrderFulfillment) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f5d4cf0fc9e41b, []int{5}
}

func (m *OrderFulfillment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderFulfillment.Unmarshal(m, b)
}
func (m *OrderFulfillment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderFulfillment.Marshal(b, m, deterministic)
}
func (m *OrderFulfillment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderFulfillment.Merge(m, src)
}
func (m *OrderFulfillment) XXX_Size() int {
	return xxx_messageInfo_OrderFulfillment.Size(m)
}
func (m *OrderFulfillment) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderFulfillment.DiscardUnknown(m)
}

var xxx_messageInfo_OrderFulfillment proto.InternalMessageInfo

type OrderComplete struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderComplete) Reset()         { *m = OrderComplete{} }
func (m *OrderComplete) String() string { return proto.CompactTextString(m) }
func (*OrderComplete) ProtoMessage()    {}
func (*OrderComplete) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f5d4cf0fc9e41b, []int{6}
}

func (m *OrderComplete) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderComplete.Unmarshal(m, b)
}
func (m *OrderComplete) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderComplete.Marshal(b, m, deterministic)
}
func (m *OrderComplete) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderComplete.Merge(m, src)
}
func (m *OrderComplete) XXX_Size() int {
	return xxx_messageInfo_OrderComplete.Size(m)
}
func (m *OrderComplete) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderComplete.DiscardUnknown(m)
}

var xxx_messageInfo_OrderComplete proto.InternalMessageInfo

type DisputeOpen struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisputeOpen) Reset()         { *m = DisputeOpen{} }
func (m *DisputeOpen) String() string { return proto.CompactTextString(m) }
func (*DisputeOpen) ProtoMessage()    {}
func (*DisputeOpen) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f5d4cf0fc9e41b, []int{7}
}

func (m *DisputeOpen) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisputeOpen.Unmarshal(m, b)
}
func (m *DisputeOpen) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisputeOpen.Marshal(b, m, deterministic)
}
func (m *DisputeOpen) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisputeOpen.Merge(m, src)
}
func (m *DisputeOpen) XXX_Size() int {
	return xxx_messageInfo_DisputeOpen.Size(m)
}
func (m *DisputeOpen) XXX_DiscardUnknown() {
	xxx_messageInfo_DisputeOpen.DiscardUnknown(m)
}

var xxx_messageInfo_DisputeOpen proto.InternalMessageInfo

type DisputeUpdate struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisputeUpdate) Reset()         { *m = DisputeUpdate{} }
func (m *DisputeUpdate) String() string { return proto.CompactTextString(m) }
func (*DisputeUpdate) ProtoMessage()    {}
func (*DisputeUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f5d4cf0fc9e41b, []int{8}
}

func (m *DisputeUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisputeUpdate.Unmarshal(m, b)
}
func (m *DisputeUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisputeUpdate.Marshal(b, m, deterministic)
}
func (m *DisputeUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisputeUpdate.Merge(m, src)
}
func (m *DisputeUpdate) XXX_Size() int {
	return xxx_messageInfo_DisputeUpdate.Size(m)
}
func (m *DisputeUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_DisputeUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_DisputeUpdate proto.InternalMessageInfo

type DisputeClose struct {
	TransactionID        string   `protobuf:"bytes,1,opt,name=transactionID,proto3" json:"transactionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisputeClose) Reset()         { *m = DisputeClose{} }
func (m *DisputeClose) String() string { return proto.CompactTextString(m) }
func (*DisputeClose) ProtoMessage()    {}
func (*DisputeClose) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f5d4cf0fc9e41b, []int{9}
}

func (m *DisputeClose) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisputeClose.Unmarshal(m, b)
}
func (m *DisputeClose) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisputeClose.Marshal(b, m, deterministic)
}
func (m *DisputeClose) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisputeClose.Merge(m, src)
}
func (m *DisputeClose) XXX_Size() int {
	return xxx_messageInfo_DisputeClose.Size(m)
}
func (m *DisputeClose) XXX_DiscardUnknown() {
	xxx_messageInfo_DisputeClose.DiscardUnknown(m)
}

var xxx_messageInfo_DisputeClose proto.InternalMessageInfo

func (m *DisputeClose) GetTransactionID() string {
	if m != nil {
		return m.TransactionID
	}
	return ""
}

type Refund struct {
	// Types that are valid to be assigned to RefundInfo:
	//	*Refund_TransactionID
	//	*Refund_ReleaseInfo
	RefundInfo           isRefund_RefundInfo `protobuf_oneof:"refundInfo"`
	Amount               string              `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	MessageSignature     []byte              `protobuf:"bytes,4,opt,name=messageSignature,proto3" json:"messageSignature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Refund) Reset()         { *m = Refund{} }
func (m *Refund) String() string { return proto.CompactTextString(m) }
func (*Refund) ProtoMessage()    {}
func (*Refund) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f5d4cf0fc9e41b, []int{10}
}

func (m *Refund) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Refund.Unmarshal(m, b)
}
func (m *Refund) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Refund.Marshal(b, m, deterministic)
}
func (m *Refund) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Refund.Merge(m, src)
}
func (m *Refund) XXX_Size() int {
	return xxx_messageInfo_Refund.Size(m)
}
func (m *Refund) XXX_DiscardUnknown() {
	xxx_messageInfo_Refund.DiscardUnknown(m)
}

var xxx_messageInfo_Refund proto.InternalMessageInfo

type isRefund_RefundInfo interface {
	isRefund_RefundInfo()
}

type Refund_TransactionID struct {
	TransactionID string `protobuf:"bytes,1,opt,name=transactionID,proto3,oneof"`
}

type Refund_ReleaseInfo struct {
	ReleaseInfo *Refund_EscrowRelease `protobuf:"bytes,2,opt,name=releaseInfo,proto3,oneof"`
}

func (*Refund_TransactionID) isRefund_RefundInfo() {}

func (*Refund_ReleaseInfo) isRefund_RefundInfo() {}

func (m *Refund) GetRefundInfo() isRefund_RefundInfo {
	if m != nil {
		return m.RefundInfo
	}
	return nil
}

func (m *Refund) GetTransactionID() string {
	if x, ok := m.GetRefundInfo().(*Refund_TransactionID); ok {
		return x.TransactionID
	}
	return ""
}

func (m *Refund) GetReleaseInfo() *Refund_EscrowRelease {
	if x, ok := m.GetRefundInfo().(*Refund_ReleaseInfo); ok {
		return x.ReleaseInfo
	}
	return nil
}

func (m *Refund) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *Refund) GetMessageSignature() []byte {
	if m != nil {
		return m.MessageSignature
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Refund) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Refund_TransactionID)(nil),
		(*Refund_ReleaseInfo)(nil),
	}
}

type Refund_EscrowRelease struct {
	EscrowSignatures     []*Refund_Signature `protobuf:"bytes,1,rep,name=escrowSignatures,proto3" json:"escrowSignatures,omitempty"`
	FromIDs              [][]byte            `protobuf:"bytes,2,rep,name=fromIDs,proto3" json:"fromIDs,omitempty"`
	ToAddress            string              `protobuf:"bytes,3,opt,name=toAddress,proto3" json:"toAddress,omitempty"`
	ToAmount             string              `protobuf:"bytes,4,opt,name=toAmount,proto3" json:"toAmount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Refund_EscrowRelease) Reset()         { *m = Refund_EscrowRelease{} }
func (m *Refund_EscrowRelease) String() string { return proto.CompactTextString(m) }
func (*Refund_EscrowRelease) ProtoMessage()    {}
func (*Refund_EscrowRelease) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f5d4cf0fc9e41b, []int{10, 0}
}

func (m *Refund_EscrowRelease) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Refund_EscrowRelease.Unmarshal(m, b)
}
func (m *Refund_EscrowRelease) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Refund_EscrowRelease.Marshal(b, m, deterministic)
}
func (m *Refund_EscrowRelease) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Refund_EscrowRelease.Merge(m, src)
}
func (m *Refund_EscrowRelease) XXX_Size() int {
	return xxx_messageInfo_Refund_EscrowRelease.Size(m)
}
func (m *Refund_EscrowRelease) XXX_DiscardUnknown() {
	xxx_messageInfo_Refund_EscrowRelease.DiscardUnknown(m)
}

var xxx_messageInfo_Refund_EscrowRelease proto.InternalMessageInfo

func (m *Refund_EscrowRelease) GetEscrowSignatures() []*Refund_Signature {
	if m != nil {
		return m.EscrowSignatures
	}
	return nil
}

func (m *Refund_EscrowRelease) GetFromIDs() [][]byte {
	if m != nil {
		return m.FromIDs
	}
	return nil
}

func (m *Refund_EscrowRelease) GetToAddress() string {
	if m != nil {
		return m.ToAddress
	}
	return ""
}

func (m *Refund_EscrowRelease) GetToAmount() string {
	if m != nil {
		return m.ToAmount
	}
	return ""
}

type Refund_Signature struct {
	From                 []byte   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Index                uint32   `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Refund_Signature) Reset()         { *m = Refund_Signature{} }
func (m *Refund_Signature) String() string { return proto.CompactTextString(m) }
func (*Refund_Signature) ProtoMessage()    {}
func (*Refund_Signature) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f5d4cf0fc9e41b, []int{10, 1}
}

func (m *Refund_Signature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Refund_Signature.Unmarshal(m, b)
}
func (m *Refund_Signature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Refund_Signature.Marshal(b, m, deterministic)
}
func (m *Refund_Signature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Refund_Signature.Merge(m, src)
}
func (m *Refund_Signature) XXX_Size() int {
	return xxx_messageInfo_Refund_Signature.Size(m)
}
func (m *Refund_Signature) XXX_DiscardUnknown() {
	xxx_messageInfo_Refund_Signature.DiscardUnknown(m)
}

var xxx_messageInfo_Refund_Signature proto.InternalMessageInfo

func (m *Refund_Signature) GetFrom() []byte {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Refund_Signature) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *Refund_Signature) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

type PaymentSent struct {
	TransactionID        string   `protobuf:"bytes,1,opt,name=transactionID,proto3" json:"transactionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaymentSent) Reset()         { *m = PaymentSent{} }
func (m *PaymentSent) String() string { return proto.CompactTextString(m) }
func (*PaymentSent) ProtoMessage()    {}
func (*PaymentSent) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f5d4cf0fc9e41b, []int{11}
}

func (m *PaymentSent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentSent.Unmarshal(m, b)
}
func (m *PaymentSent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentSent.Marshal(b, m, deterministic)
}
func (m *PaymentSent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentSent.Merge(m, src)
}
func (m *PaymentSent) XXX_Size() int {
	return xxx_messageInfo_PaymentSent.Size(m)
}
func (m *PaymentSent) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentSent.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentSent proto.InternalMessageInfo

func (m *PaymentSent) GetTransactionID() string {
	if m != nil {
		return m.TransactionID
	}
	return ""
}

type PaymentFinalized struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaymentFinalized) Reset()         { *m = PaymentFinalized{} }
func (m *PaymentFinalized) String() string { return proto.CompactTextString(m) }
func (*PaymentFinalized) ProtoMessage()    {}
func (*PaymentFinalized) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f5d4cf0fc9e41b, []int{12}
}

func (m *PaymentFinalized) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentFinalized.Unmarshal(m, b)
}
func (m *PaymentFinalized) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentFinalized.Marshal(b, m, deterministic)
}
func (m *PaymentFinalized) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentFinalized.Merge(m, src)
}
func (m *PaymentFinalized) XXX_Size() int {
	return xxx_messageInfo_PaymentFinalized.Size(m)
}
func (m *PaymentFinalized) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentFinalized.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentFinalized proto.InternalMessageInfo

type PaymentSentList struct {
	Messages             []*PaymentSent `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PaymentSentList) Reset()         { *m = PaymentSentList{} }
func (m *PaymentSentList) String() string { return proto.CompactTextString(m) }
func (*PaymentSentList) ProtoMessage()    {}
func (*PaymentSentList) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f5d4cf0fc9e41b, []int{13}
}

func (m *PaymentSentList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentSentList.Unmarshal(m, b)
}
func (m *PaymentSentList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentSentList.Marshal(b, m, deterministic)
}
func (m *PaymentSentList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentSentList.Merge(m, src)
}
func (m *PaymentSentList) XXX_Size() int {
	return xxx_messageInfo_PaymentSentList.Size(m)
}
func (m *PaymentSentList) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentSentList.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentSentList proto.InternalMessageInfo

func (m *PaymentSentList) GetMessages() []*PaymentSent {
	if m != nil {
		return m.Messages
	}
	return nil
}

type RefundList struct {
	Messages             []*Refund `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RefundList) Reset()         { *m = RefundList{} }
func (m *RefundList) String() string { return proto.CompactTextString(m) }
func (*RefundList) ProtoMessage()    {}
func (*RefundList) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f5d4cf0fc9e41b, []int{14}
}

func (m *RefundList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefundList.Unmarshal(m, b)
}
func (m *RefundList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefundList.Marshal(b, m, deterministic)
}
func (m *RefundList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefundList.Merge(m, src)
}
func (m *RefundList) XXX_Size() int {
	return xxx_messageInfo_RefundList.Size(m)
}
func (m *RefundList) XXX_DiscardUnknown() {
	xxx_messageInfo_RefundList.DiscardUnknown(m)
}

var xxx_messageInfo_RefundList proto.InternalMessageInfo

func (m *RefundList) GetMessages() []*Refund {
	if m != nil {
		return m.Messages
	}
	return nil
}

func init() {
	proto.RegisterEnum("OrderOpen_Payment_Method", OrderOpen_Payment_Method_name, OrderOpen_Payment_Method_value)
	proto.RegisterEnum("OrderReject_RejectType", OrderReject_RejectType_name, OrderReject_RejectType_value)
	proto.RegisterType((*OrderOpen)(nil), "OrderOpen")
	proto.RegisterType((*OrderOpen_Shipping)(nil), "OrderOpen.Shipping")
	proto.RegisterType((*OrderOpen_Item)(nil), "OrderOpen.Item")
	proto.RegisterType((*OrderOpen_Item_Option)(nil), "OrderOpen.Item.Option")
	proto.RegisterType((*OrderOpen_Item_ShippingOption)(nil), "OrderOpen.Item.ShippingOption")
	proto.RegisterType((*OrderOpen_Payment)(nil), "OrderOpen.Payment")
	proto.RegisterType((*OrderReject)(nil), "OrderReject")
	proto.RegisterType((*OrderConfirmation)(nil), "OrderConfirmation")
	proto.RegisterType((*OrderCancel)(nil), "OrderCancel")
	proto.RegisterType((*RatingSignatures)(nil), "RatingSignatures")
	proto.RegisterType((*RatingSignatures_RatingSignature)(nil), "RatingSignatures.RatingSignature")
	proto.RegisterType((*OrderFulfillment)(nil), "OrderFulfillment")
	proto.RegisterType((*OrderComplete)(nil), "OrderComplete")
	proto.RegisterType((*DisputeOpen)(nil), "DisputeOpen")
	proto.RegisterType((*DisputeUpdate)(nil), "DisputeUpdate")
	proto.RegisterType((*DisputeClose)(nil), "DisputeClose")
	proto.RegisterType((*Refund)(nil), "Refund")
	proto.RegisterType((*Refund_EscrowRelease)(nil), "Refund.EscrowRelease")
	proto.RegisterType((*Refund_Signature)(nil), "Refund.Signature")
	proto.RegisterType((*PaymentSent)(nil), "PaymentSent")
	proto.RegisterType((*PaymentFinalized)(nil), "PaymentFinalized")
	proto.RegisterType((*PaymentSentList)(nil), "PaymentSentList")
	proto.RegisterType((*RefundList)(nil), "RefundList")
}

func init() { proto.RegisterFile("orders.proto", fileDescriptor_e0f5d4cf0fc9e41b) }

var fileDescriptor_e0f5d4cf0fc9e41b = []byte{
	// 1214 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xcd, 0x8e, 0x1b, 0x45,
	0x10, 0x8e, 0xd7, 0x5e, 0xff, 0x94, 0x7f, 0xd6, 0x69, 0x42, 0x18, 0x2c, 0x08, 0x66, 0x08, 0x91,
	0x15, 0xd0, 0x84, 0xec, 0x82, 0x04, 0x42, 0x20, 0x39, 0xb6, 0x57, 0x31, 0xd9, 0x64, 0x51, 0x7b,
	0xc3, 0x81, 0x4b, 0xd4, 0x3b, 0x53, 0xeb, 0x1d, 0x34, 0xd3, 0x3d, 0x4c, 0xb7, 0x03, 0xe6, 0xc8,
	0x13, 0xf0, 0x0c, 0xbc, 0x02, 0x07, 0xde, 0x83, 0x2b, 0x57, 0x1e, 0x04, 0x75, 0x4f, 0x8f, 0x3d,
	0xfe, 0x89, 0x14, 0x0e, 0x9c, 0xec, 0xfa, 0xaa, 0xaa, 0x7f, 0xbe, 0xfa, 0xaa, 0x7a, 0xa0, 0x25,
	0xd2, 0x00, 0x53, 0xe9, 0x25, 0xa9, 0x50, 0xa2, 0xf7, 0xde, 0x5c, 0x88, 0x79, 0x84, 0x0f, 0x8c,
	0x75, 0xb9, 0xb8, 0x7a, 0xa0, 0xc2, 0x18, 0xa5, 0x62, 0x71, 0x62, 0x03, 0x88, 0x2f, 0x16, 0x5c,
	0xa5, 0x4b, 0x5f, 0x04, 0x98, 0x27, 0xb5, 0xa3, 0x50, 0xaa, 0x90, 0xcf, 0xad, 0xd9, 0xf2, 0x45,
	0x1c, 0x0b, 0x9e, 0x59, 0xee, 0xaf, 0x4d, 0x68, 0x9c, 0xeb, 0x2d, 0xce, 0x13, 0xe4, 0xe4, 0x3e,
	0xd4, 0x6d, 0xb0, 0x74, 0x4a, 0xfd, 0xf2, 0xa0, 0x79, 0xdc, 0xf1, 0x66, 0xe1, 0x9c, 0x63, 0x70,
	0x96, 0xc1, 0x74, 0xe5, 0x27, 0x77, 0xa1, 0x9d, 0xe2, 0xd5, 0x82, 0x07, 0xc3, 0x20, 0x48, 0x51,
	0x4a, 0xe7, 0xa0, 0x5f, 0x1a, 0x34, 0xe8, 0x26, 0x48, 0x1e, 0x40, 0x5d, 0x5e, 0x87, 0x49, 0x12,
	0xf2, 0xb9, 0x53, 0xee, 0x97, 0x06, 0xcd, 0xe3, 0x37, 0xbc, 0xd5, 0x7e, 0xde, 0xcc, 0xba, 0xe8,
	0x2a, 0x88, 0xbc, 0x0b, 0xb5, 0xcb, 0xc5, 0x12, 0xd3, 0xe9, 0xd8, 0xa9, 0x98, 0xf8, 0xb2, 0x37,
	0x1d, 0xd3, 0x1c, 0x23, 0x9f, 0x43, 0x63, 0x75, 0x67, 0xe7, 0xd0, 0x04, 0xf4, 0xbc, 0x8c, 0x15,
	0x2f, 0x67, 0xc5, 0xbb, 0xc8, 0x23, 0xe8, 0x3a, 0x98, 0x7c, 0x08, 0x87, 0xa1, 0xc2, 0x58, 0x3a,
	0x55, 0x73, 0xb1, 0xa3, 0xc2, 0x31, 0xa6, 0x0a, 0x63, 0x9a, 0x79, 0xc9, 0xc7, 0x50, 0x4b, 0xd8,
	0x32, 0x46, 0xae, 0x9c, 0x9a, 0x59, 0x9e, 0x14, 0x02, 0xbf, 0xcd, 0x3c, 0x34, 0x0f, 0x21, 0x77,
	0x00, 0x52, 0xa6, 0xf9, 0x78, 0x82, 0x4b, 0xe9, 0xd4, 0xfb, 0xe5, 0x41, 0x8b, 0x16, 0x10, 0x72,
	0x0c, 0xb7, 0x58, 0xa4, 0x30, 0xe5, 0x4c, 0xe1, 0x48, 0x70, 0xc5, 0x7c, 0x35, 0xe5, 0x57, 0xc2,
	0x69, 0x18, 0xae, 0xf6, 0xfa, 0xc8, 0x7d, 0xe8, 0xc6, 0x28, 0x25, 0x9b, 0xa3, 0xa6, 0x9e, 0xa9,
	0x45, 0x8a, 0x0e, 0xf4, 0x4b, 0x83, 0x16, 0xdd, 0xc1, 0x7b, 0x7f, 0x95, 0xa0, 0x9e, 0x93, 0x48,
	0x6e, 0x43, 0x55, 0xd3, 0x78, 0x21, 0x9c, 0x92, 0x59, 0xde, 0x5a, 0xc4, 0x81, 0x1a, 0xdb, 0xa8,
	0x51, 0x6e, 0x12, 0x02, 0x15, 0x3f, 0x54, 0x4b, 0x53, 0x99, 0x06, 0x35, 0xff, 0xc9, 0x2d, 0x38,
	0x94, 0x8a, 0x29, 0x34, 0xf4, 0x37, 0x68, 0x66, 0xe8, 0x8b, 0x26, 0x42, 0x2a, 0x16, 0x8d, 0x44,
	0x80, 0x86, 0xf8, 0x06, 0x2d, 0x20, 0xe4, 0x1e, 0xd4, 0xac, 0xf4, 0x9c, 0x6a, 0xbf, 0x34, 0xe8,
	0x1c, 0xb7, 0xbc, 0x51, 0x66, 0x6b, 0x37, 0xcd, 0x9d, 0xc4, 0x85, 0x96, 0xdd, 0xfc, 0x99, 0x50,
	0x28, 0x0d, 0xc7, 0x0d, 0xba, 0x81, 0xf5, 0x7e, 0x2b, 0x43, 0x45, 0x97, 0x84, 0xf4, 0xa1, 0x69,
	0xe5, 0xf6, 0x98, 0xc9, 0x6b, 0x7b, 0xab, 0x22, 0x44, 0x7a, 0x50, 0xff, 0x71, 0xc1, 0xb8, 0xd2,
	0x97, 0xc8, 0xee, 0xb6, 0xb2, 0xc9, 0x27, 0x50, 0x13, 0x89, 0x0a, 0x05, 0x97, 0x4e, 0xd9, 0x94,
	0xfc, 0xf6, 0x56, 0xc9, 0xbd, 0x73, 0xe3, 0xa6, 0x79, 0x18, 0x39, 0x85, 0x4e, 0xae, 0xc3, 0xcc,
	0x65, 0x25, 0x78, 0x67, 0x3b, 0x71, 0xb6, 0x11, 0x45, 0xb7, 0xb2, 0x34, 0xad, 0x31, 0xc6, 0xc2,
	0xd2, 0x64, 0xfe, 0xeb, 0xbb, 0xf8, 0x62, 0x91, 0x08, 0xae, 0xf9, 0xc8, 0x44, 0xd8, 0xa0, 0x45,
	0x88, 0xdc, 0x83, 0x8e, 0x95, 0x55, 0xde, 0x51, 0x19, 0x39, 0x5b, 0x68, 0xef, 0x18, 0xaa, 0xeb,
	0x7d, 0x38, 0x8b, 0xd1, 0x12, 0x63, 0xfe, 0xeb, 0xf2, 0xbd, 0x64, 0xd1, 0x02, 0x2d, 0x1d, 0x99,
	0xd1, 0xfb, 0x1a, 0x3a, 0xb3, 0x9d, 0x33, 0xee, 0xe4, 0x3a, 0x50, 0x93, 0x98, 0xbe, 0x0c, 0xfd,
	0x3c, 0x3b, 0x37, 0x7b, 0x7f, 0x1f, 0x40, 0xcd, 0x8a, 0x9f, 0x3c, 0x84, 0x6a, 0x8c, 0xea, 0x5a,
	0x04, 0x26, 0xb7, 0x73, 0xfc, 0xf6, 0x6e, 0x83, 0x78, 0x4f, 0x4d, 0x00, 0xb5, 0x81, 0xe4, 0x1d,
	0x68, 0xc4, 0x22, 0xc0, 0x94, 0x29, 0x91, 0xda, 0xa5, 0xd7, 0x80, 0xd6, 0x2d, 0x8b, 0xb5, 0x3e,
	0xac, 0x0e, 0xad, 0xa5, 0xb3, 0xfc, 0x6b, 0x16, 0x72, 0x3d, 0xcc, 0xac, 0x1a, 0xd7, 0x40, 0x51,
	0xd5, 0x87, 0x9b, 0xaa, 0xd6, 0x7d, 0xe0, 0xa7, 0x61, 0xa2, 0x8c, 0x14, 0x75, 0x1f, 0x18, 0x4b,
	0x6b, 0x6f, 0xb5, 0xe9, 0x13, 0x5c, 0x1a, 0x7a, 0x5b, 0x74, 0x03, 0x33, 0x1d, 0x21, 0x42, 0xee,
	0xd4, 0x6d, 0x47, 0x88, 0x50, 0x4f, 0xc5, 0x2e, 0x4a, 0x3f, 0x15, 0x3f, 0x51, 0x8c, 0x90, 0x49,
	0x3c, 0x45, 0xb4, 0x0d, 0xbc, 0x83, 0xbb, 0x27, 0x50, 0xcd, 0xee, 0x4e, 0x00, 0xaa, 0xe3, 0x29,
	0x9d, 0x8c, 0x2e, 0xba, 0x37, 0x48, 0x07, 0x60, 0x34, 0x7c, 0x36, 0x9a, 0x9c, 0x0d, 0x1f, 0x9d,
	0x4d, 0xba, 0x25, 0xd2, 0x86, 0xc6, 0xd3, 0xf3, 0xf1, 0x84, 0x0e, 0x2f, 0x26, 0xe3, 0xee, 0x81,
	0xfb, 0x47, 0x09, 0x9a, 0x86, 0x43, 0x8a, 0x3f, 0xa0, 0xaf, 0xc8, 0x47, 0x50, 0x51, 0xcb, 0x04,
	0x2d, 0xbf, 0x6f, 0x79, 0x05, 0x9f, 0x97, 0xfd, 0x5c, 0x2c, 0x13, 0xa4, 0x26, 0x48, 0xdf, 0x36,
	0x45, 0x26, 0x05, 0xb7, 0xc4, 0x5a, 0x6b, 0xef, 0x18, 0x29, 0xef, 0x1f, 0x23, 0xee, 0x09, 0xc0,
	0x7a, 0x5d, 0x72, 0x04, 0xcd, 0xe7, 0xb3, 0x09, 0x7d, 0x41, 0x27, 0xdf, 0x64, 0xc7, 0xbf, 0x05,
	0xdd, 0xef, 0x86, 0x67, 0xd3, 0xf1, 0xf0, 0x62, 0x7a, 0xfe, 0xec, 0xc5, 0x84, 0xd2, 0x73, 0xda,
	0x2d, 0xb9, 0x08, 0x37, 0xcd, 0xc1, 0x46, 0x82, 0x5f, 0x85, 0x69, 0xcc, 0x8c, 0xac, 0xee, 0x42,
	0x5b, 0xa5, 0x8c, 0x4b, 0xe6, 0x6b, 0x73, 0x3a, 0xb6, 0xfa, 0xda, 0x04, 0xf7, 0x9e, 0xed, 0xe0,
	0x15, 0x67, 0x7b, 0x61, 0xb9, 0x19, 0x31, 0xee, 0x63, 0xf4, 0x3f, 0x6c, 0xf0, 0x4f, 0x09, 0xba,
	0xd4, 0x8c, 0xec, 0x15, 0x26, 0xc9, 0x67, 0x50, 0x91, 0xe1, 0xea, 0x15, 0x7c, 0xdf, 0xdb, 0x0e,
	0xd8, 0x06, 0xa8, 0x09, 0xff, 0x2f, 0xfb, 0xf6, 0x62, 0x38, 0xda, 0x5a, 0x44, 0xab, 0x4f, 0x46,
	0x8b, 0x79, 0xde, 0x94, 0xfa, 0xbf, 0xee, 0x82, 0xd5, 0x83, 0x62, 0xd7, 0x5a, 0x03, 0x64, 0x00,
	0x47, 0x2f, 0x91, 0x07, 0x22, 0xdd, 0x2e, 0xf2, 0x36, 0xec, 0x12, 0xe8, 0x1a, 0x1e, 0x4f, 0x17,
	0xd1, 0x55, 0x18, 0x45, 0xba, 0x4d, 0xdd, 0x23, 0x68, 0xdb, 0x12, 0xc6, 0x49, 0x84, 0x0a, 0xdd,
	0x36, 0x34, 0xc7, 0xa1, 0x4c, 0x16, 0x0a, 0x75, 0x3b, 0x6b, 0xbf, 0x35, 0x9f, 0x27, 0x01, 0x53,
	0xe8, 0x7e, 0x0a, 0x2d, 0x0b, 0x8c, 0x22, 0x21, 0xf1, 0xf5, 0xaa, 0xe1, 0xfe, 0x59, 0x86, 0x2a,
	0x35, 0x9f, 0x05, 0xe4, 0xde, 0xde, 0x84, 0xc7, 0x37, 0xb6, 0x0b, 0xf8, 0x05, 0x34, 0xd3, 0xac,
	0xab, 0xcc, 0x7b, 0x79, 0x60, 0xe6, 0xf0, 0x9b, 0x5e, 0xb6, 0x8a, 0x37, 0x29, 0xb6, 0xdd, 0xe3,
	0x1b, 0xb4, 0x18, 0xfb, 0xca, 0x71, 0xb2, 0xaf, 0x36, 0x95, 0x57, 0xd4, 0xe6, 0xf7, 0x12, 0xb4,
	0x37, 0x36, 0x21, 0x5f, 0xe5, 0x43, 0x60, 0xad, 0x01, 0x2b, 0x8e, 0x9b, 0xf9, 0xa9, 0xd6, 0x62,
	0xd8, 0x09, 0xd5, 0xd3, 0xea, 0x2a, 0x15, 0xf1, 0x74, 0xac, 0xdf, 0x60, 0xfd, 0x95, 0x90, 0x9b,
	0xba, 0xbe, 0x4a, 0xe4, 0x13, 0x3f, 0x3b, 0xf1, 0x1a, 0xd0, 0x0f, 0x9c, 0x12, 0xc3, 0xec, 0x3a,
	0xd9, 0x08, 0x5c, 0xd9, 0xbd, 0x19, 0x34, 0x36, 0xa4, 0xa3, 0x57, 0x34, 0x7c, 0xb6, 0xa8, 0xf9,
	0xaf, 0x97, 0x96, 0x5b, 0x32, 0x5c, 0x03, 0xfa, 0xa5, 0x08, 0x79, 0x80, 0x3f, 0x9b, 0x4d, 0xdb,
	0x34, 0x33, 0x1e, 0xb5, 0x00, 0xb2, 0x2f, 0x38, 0xcd, 0xa5, 0x7b, 0x02, 0x4d, 0x3b, 0xd2, 0x67,
	0x7a, 0xf4, 0xbf, 0x5e, 0xb9, 0x09, 0x74, 0x6d, 0xd2, 0x69, 0xc8, 0x59, 0x14, 0xfe, 0x82, 0x81,
	0xfb, 0x25, 0x1c, 0x15, 0x16, 0xd2, 0x5f, 0x93, 0x64, 0x00, 0x75, 0xcb, 0x7b, 0xce, 0x64, 0xcb,
	0x2b, 0xc4, 0xd0, 0x95, 0xd7, 0x7d, 0xa8, 0xc7, 0x93, 0x3e, 0x93, 0xc9, 0xfb, 0x60, 0x27, 0xaf,
	0x66, 0x2b, 0xb0, 0x4e, 0x79, 0x54, 0xf9, 0xfe, 0x20, 0xb9, 0xbc, 0xac, 0x9a, 0x4f, 0xc2, 0x93,
	0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x95, 0x2b, 0xc8, 0x09, 0x46, 0x0b, 0x00, 0x00,
}
