// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message_MessageType int32

const (
	Message_ACK      Message_MessageType = 0
	Message_PING     Message_MessageType = 1
	Message_CHAT     Message_MessageType = 2
	Message_FOLLOW   Message_MessageType = 3
	Message_UNFOLLOW Message_MessageType = 4
	Message_STORE    Message_MessageType = 5
	Message_ORDER    Message_MessageType = 6
)

var Message_MessageType_name = map[int32]string{
	0: "ACK",
	1: "PING",
	2: "CHAT",
	3: "FOLLOW",
	4: "UNFOLLOW",
	5: "STORE",
	6: "ORDER",
}

var Message_MessageType_value = map[string]int32{
	"ACK":      0,
	"PING":     1,
	"CHAT":     2,
	"FOLLOW":   3,
	"UNFOLLOW": 4,
	"STORE":    5,
	"ORDER":    6,
}

func (x Message_MessageType) String() string {
	return proto.EnumName(Message_MessageType_name, int32(x))
}

func (Message_MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0, 0}
}

type ChatMessage_Flag int32

const (
	ChatMessage_MESSAGE ChatMessage_Flag = 0
	ChatMessage_TYPING  ChatMessage_Flag = 1
	ChatMessage_READ    ChatMessage_Flag = 2
)

var ChatMessage_Flag_name = map[int32]string{
	0: "MESSAGE",
	1: "TYPING",
	2: "READ",
}

var ChatMessage_Flag_value = map[string]int32{
	"MESSAGE": 0,
	"TYPING":  1,
	"READ":    2,
}

func (x ChatMessage_Flag) String() string {
	return proto.EnumName(ChatMessage_Flag_name, int32(x))
}

func (ChatMessage_Flag) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1, 0}
}

type OrderMessage_MessageType int32

const (
	OrderMessage_ORDER_OPEN         OrderMessage_MessageType = 0
	OrderMessage_ORDER_REJECT       OrderMessage_MessageType = 1
	OrderMessage_ORDER_CANCEL       OrderMessage_MessageType = 2
	OrderMessage_ORDER_CONFIRMATION OrderMessage_MessageType = 3
	OrderMessage_ORDER_FULFILLMENT  OrderMessage_MessageType = 4
	OrderMessage_ORDER_COMPLETE     OrderMessage_MessageType = 5
	OrderMessage_DISPUTE_OPEN       OrderMessage_MessageType = 6
	OrderMessage_DISPUTE_UPDATE     OrderMessage_MessageType = 7
	OrderMessage_DISPUTE_CLOSE      OrderMessage_MessageType = 8
	OrderMessage_REFUND             OrderMessage_MessageType = 9
	OrderMessage_PAYMENT_SENT       OrderMessage_MessageType = 10
	OrderMessage_PAYMENT_FINALIZED  OrderMessage_MessageType = 11
)

var OrderMessage_MessageType_name = map[int32]string{
	0:  "ORDER_OPEN",
	1:  "ORDER_REJECT",
	2:  "ORDER_CANCEL",
	3:  "ORDER_CONFIRMATION",
	4:  "ORDER_FULFILLMENT",
	5:  "ORDER_COMPLETE",
	6:  "DISPUTE_OPEN",
	7:  "DISPUTE_UPDATE",
	8:  "DISPUTE_CLOSE",
	9:  "REFUND",
	10: "PAYMENT_SENT",
	11: "PAYMENT_FINALIZED",
}

var OrderMessage_MessageType_value = map[string]int32{
	"ORDER_OPEN":         0,
	"ORDER_REJECT":       1,
	"ORDER_CANCEL":       2,
	"ORDER_CONFIRMATION": 3,
	"ORDER_FULFILLMENT":  4,
	"ORDER_COMPLETE":     5,
	"DISPUTE_OPEN":       6,
	"DISPUTE_UPDATE":     7,
	"DISPUTE_CLOSE":      8,
	"REFUND":             9,
	"PAYMENT_SENT":       10,
	"PAYMENT_FINALIZED":  11,
}

func (x OrderMessage_MessageType) String() string {
	return proto.EnumName(OrderMessage_MessageType_name, int32(x))
}

func (OrderMessage_MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4, 0}
}

type Message struct {
	MessageType          Message_MessageType `protobuf:"varint,1,opt,name=messageType,proto3,enum=Message_MessageType" json:"messageType,omitempty"`
	MessageID            string              `protobuf:"bytes,2,opt,name=messageID,proto3" json:"messageID,omitempty"`
	Sequence             uint32              `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Payload              *any.Any            `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetMessageType() Message_MessageType {
	if m != nil {
		return m.MessageType
	}
	return Message_ACK
}

func (m *Message) GetMessageID() string {
	if m != nil {
		return m.MessageID
	}
	return ""
}

func (m *Message) GetSequence() uint32 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *Message) GetPayload() *any.Any {
	if m != nil {
		return m.Payload
	}
	return nil
}

type ChatMessage struct {
	Subject   string               `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Message   string               `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp *timestamp.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Flag      ChatMessage_Flag     `protobuf:"varint,4,opt,name=flag,proto3,enum=ChatMessage_Flag" json:"flag,omitempty"`
	// Only used when Flag is READ.
	ReadID               string   `protobuf:"bytes,5,opt,name=readID,proto3" json:"readID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatMessage) Reset()         { *m = ChatMessage{} }
func (m *ChatMessage) String() string { return proto.CompactTextString(m) }
func (*ChatMessage) ProtoMessage()    {}
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *ChatMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatMessage.Unmarshal(m, b)
}
func (m *ChatMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatMessage.Marshal(b, m, deterministic)
}
func (m *ChatMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatMessage.Merge(m, src)
}
func (m *ChatMessage) XXX_Size() int {
	return xxx_messageInfo_ChatMessage.Size(m)
}
func (m *ChatMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ChatMessage proto.InternalMessageInfo

func (m *ChatMessage) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *ChatMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ChatMessage) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *ChatMessage) GetFlag() ChatMessage_Flag {
	if m != nil {
		return m.Flag
	}
	return ChatMessage_MESSAGE
}

func (m *ChatMessage) GetReadID() string {
	if m != nil {
		return m.ReadID
	}
	return ""
}

type StoreMessage struct {
	Cids                 [][]byte `protobuf:"bytes,1,rep,name=cids,proto3" json:"cids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoreMessage) Reset()         { *m = StoreMessage{} }
func (m *StoreMessage) String() string { return proto.CompactTextString(m) }
func (*StoreMessage) ProtoMessage()    {}
func (*StoreMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *StoreMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreMessage.Unmarshal(m, b)
}
func (m *StoreMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreMessage.Marshal(b, m, deterministic)
}
func (m *StoreMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreMessage.Merge(m, src)
}
func (m *StoreMessage) XXX_Size() int {
	return xxx_messageInfo_StoreMessage.Size(m)
}
func (m *StoreMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreMessage.DiscardUnknown(m)
}

var xxx_messageInfo_StoreMessage proto.InternalMessageInfo

func (m *StoreMessage) GetCids() [][]byte {
	if m != nil {
		return m.Cids
	}
	return nil
}

type AckMessage struct {
	AckedMessageID       string   `protobuf:"bytes,1,opt,name=ackedMessageID,proto3" json:"ackedMessageID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AckMessage) Reset()         { *m = AckMessage{} }
func (m *AckMessage) String() string { return proto.CompactTextString(m) }
func (*AckMessage) ProtoMessage()    {}
func (*AckMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *AckMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AckMessage.Unmarshal(m, b)
}
func (m *AckMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AckMessage.Marshal(b, m, deterministic)
}
func (m *AckMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AckMessage.Merge(m, src)
}
func (m *AckMessage) XXX_Size() int {
	return xxx_messageInfo_AckMessage.Size(m)
}
func (m *AckMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_AckMessage.DiscardUnknown(m)
}

var xxx_messageInfo_AckMessage proto.InternalMessageInfo

func (m *AckMessage) GetAckedMessageID() string {
	if m != nil {
		return m.AckedMessageID
	}
	return ""
}

type OrderMessage struct {
	OrderID              string                   `protobuf:"bytes,1,opt,name=orderID,proto3" json:"orderID,omitempty"`
	Timestamp            *timestamp.Timestamp     `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	MessageType          OrderMessage_MessageType `protobuf:"varint,3,opt,name=messageType,proto3,enum=OrderMessage_MessageType" json:"messageType,omitempty"`
	Message              *any.Any                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *OrderMessage) Reset()         { *m = OrderMessage{} }
func (m *OrderMessage) String() string { return proto.CompactTextString(m) }
func (*OrderMessage) ProtoMessage()    {}
func (*OrderMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}

func (m *OrderMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderMessage.Unmarshal(m, b)
}
func (m *OrderMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderMessage.Marshal(b, m, deterministic)
}
func (m *OrderMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderMessage.Merge(m, src)
}
func (m *OrderMessage) XXX_Size() int {
	return xxx_messageInfo_OrderMessage.Size(m)
}
func (m *OrderMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderMessage.DiscardUnknown(m)
}

var xxx_messageInfo_OrderMessage proto.InternalMessageInfo

func (m *OrderMessage) GetOrderID() string {
	if m != nil {
		return m.OrderID
	}
	return ""
}

func (m *OrderMessage) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *OrderMessage) GetMessageType() OrderMessage_MessageType {
	if m != nil {
		return m.MessageType
	}
	return OrderMessage_ORDER_OPEN
}

func (m *OrderMessage) GetMessage() *any.Any {
	if m != nil {
		return m.Message
	}
	return nil
}

type OrderList struct {
	Messages             []*OrderMessage `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *OrderList) Reset()         { *m = OrderList{} }
func (m *OrderList) String() string { return proto.CompactTextString(m) }
func (*OrderList) ProtoMessage()    {}
func (*OrderList) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{5}
}

func (m *OrderList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderList.Unmarshal(m, b)
}
func (m *OrderList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderList.Marshal(b, m, deterministic)
}
func (m *OrderList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderList.Merge(m, src)
}
func (m *OrderList) XXX_Size() int {
	return xxx_messageInfo_OrderList.Size(m)
}
func (m *OrderList) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderList.DiscardUnknown(m)
}

var xxx_messageInfo_OrderList proto.InternalMessageInfo

func (m *OrderList) GetMessages() []*OrderMessage {
	if m != nil {
		return m.Messages
	}
	return nil
}

func init() {
	proto.RegisterEnum("Message_MessageType", Message_MessageType_name, Message_MessageType_value)
	proto.RegisterEnum("ChatMessage_Flag", ChatMessage_Flag_name, ChatMessage_Flag_value)
	proto.RegisterEnum("OrderMessage_MessageType", OrderMessage_MessageType_name, OrderMessage_MessageType_value)
	proto.RegisterType((*Message)(nil), "Message")
	proto.RegisterType((*ChatMessage)(nil), "ChatMessage")
	proto.RegisterType((*StoreMessage)(nil), "StoreMessage")
	proto.RegisterType((*AckMessage)(nil), "AckMessage")
	proto.RegisterType((*OrderMessage)(nil), "OrderMessage")
	proto.RegisterType((*OrderList)(nil), "OrderList")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 627 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x5b, 0x6e, 0x9b, 0x40,
	0x14, 0x0d, 0x86, 0xd8, 0xe6, 0x62, 0x5b, 0x93, 0x51, 0x1a, 0x91, 0xa8, 0x52, 0x2d, 0xa4, 0x56,
	0xce, 0x0f, 0x91, 0xdc, 0x2a, 0xaa, 0xd4, 0x2f, 0x0a, 0x43, 0x4a, 0x8b, 0xc1, 0x1a, 0xb0, 0xaa,
	0xe4, 0x27, 0xc2, 0xf6, 0xc4, 0x4d, 0xe3, 0x04, 0xd7, 0x90, 0x0f, 0xaf, 0xa0, 0x1b, 0xeb, 0x56,
	0xba, 0x81, 0xae, 0xa0, 0x1a, 0x60, 0xfc, 0x48, 0xd5, 0x4a, 0xfd, 0x62, 0xce, 0xb9, 0x87, 0xb9,
	0xf7, 0x9e, 0x39, 0xd0, 0xbe, 0x67, 0x59, 0x96, 0xcc, 0x98, 0xb9, 0x58, 0xa6, 0x79, 0x7a, 0x72,
	0x3c, 0x4b, 0xd3, 0xd9, 0x9c, 0x9d, 0x15, 0x68, 0xfc, 0x78, 0x73, 0x96, 0x3c, 0xac, 0xaa, 0xd2,
	0x8b, 0xa7, 0xa5, 0xfc, 0xf6, 0x9e, 0x65, 0x79, 0x72, 0xbf, 0x28, 0x05, 0xc6, 0xf7, 0x1a, 0x34,
	0x06, 0xe5, 0x6d, 0xf8, 0x1c, 0xb4, 0xea, 0xe2, 0x78, 0xb5, 0x60, 0xba, 0xd4, 0x95, 0x7a, 0x9d,
	0xfe, 0xa1, 0x59, 0x95, 0xc5, 0x97, 0xd7, 0xe8, 0xb6, 0x10, 0x3f, 0x07, 0xb5, 0x82, 0x9e, 0xa3,
	0xd7, 0xba, 0x52, 0x4f, 0xa5, 0x1b, 0x02, 0x9f, 0x40, 0x33, 0x63, 0xdf, 0x1e, 0xd9, 0xc3, 0x84,
	0xe9, 0x72, 0x57, 0xea, 0xb5, 0xe9, 0x1a, 0x63, 0x13, 0x1a, 0x8b, 0x64, 0x35, 0x4f, 0x93, 0xa9,
	0xae, 0x74, 0xa5, 0x9e, 0xd6, 0x3f, 0x34, 0xcb, 0x81, 0x4d, 0x31, 0xb0, 0x69, 0x3d, 0xac, 0xa8,
	0x10, 0x19, 0x57, 0xa0, 0x6d, 0x4d, 0x81, 0x1b, 0x20, 0x5b, 0xf6, 0x27, 0xb4, 0x87, 0x9b, 0xa0,
	0x0c, 0xbd, 0xe0, 0x02, 0x49, 0xfc, 0x64, 0x7f, 0xb0, 0x62, 0x54, 0xc3, 0x00, 0x75, 0x37, 0xf4,
	0xfd, 0xf0, 0x33, 0x92, 0x71, 0x0b, 0x9a, 0xa3, 0xa0, 0x42, 0x0a, 0x56, 0x61, 0x3f, 0x8a, 0x43,
	0x4a, 0xd0, 0x3e, 0x3f, 0x86, 0xd4, 0x21, 0x14, 0xd5, 0x8d, 0x9f, 0x12, 0x68, 0xf6, 0x97, 0x24,
	0x17, 0x6e, 0xe8, 0xd0, 0xc8, 0x1e, 0xc7, 0x5f, 0xd9, 0x24, 0x2f, 0x9c, 0x50, 0xa9, 0x80, 0xbc,
	0x52, 0xad, 0x57, 0x6d, 0x2b, 0x20, 0x7e, 0x0b, 0xea, 0xda, 0xe0, 0x62, 0x59, 0xad, 0x7f, 0xf2,
	0xc7, 0x46, 0xb1, 0x50, 0xd0, 0x8d, 0x18, 0xbf, 0x04, 0xe5, 0x66, 0x9e, 0xcc, 0x0a, 0x1b, 0x3a,
	0xfd, 0x03, 0x73, 0x6b, 0x12, 0xd3, 0x9d, 0x27, 0x33, 0x5a, 0x94, 0xf1, 0x11, 0xd4, 0x97, 0x2c,
	0x99, 0x7a, 0x8e, 0xbe, 0x5f, 0x74, 0xae, 0x90, 0x71, 0x0a, 0x0a, 0x57, 0x61, 0x0d, 0x1a, 0x03,
	0x12, 0x45, 0xd6, 0x05, 0x41, 0x7b, 0xdc, 0x81, 0xf8, 0x72, 0xe3, 0x0b, 0x25, 0x96, 0x83, 0x6a,
	0x86, 0x01, 0xad, 0x28, 0x4f, 0x97, 0x4c, 0xec, 0x89, 0x41, 0x99, 0xdc, 0x4e, 0x33, 0x5d, 0xea,
	0xca, 0xbd, 0x16, 0x2d, 0xce, 0xc6, 0x1b, 0x00, 0x6b, 0x72, 0x27, 0x14, 0xaf, 0xa0, 0x93, 0x4c,
	0xee, 0xd8, 0x74, 0xb0, 0x7e, 0xe4, 0xd2, 0x90, 0x27, 0xac, 0xf1, 0x43, 0x86, 0x56, 0xb8, 0x9c,
	0xb2, 0xe5, 0x96, 0x85, 0x29, 0xc7, 0xeb, 0x3f, 0x04, 0xdc, 0x35, 0xaa, 0xf6, 0x3f, 0x46, 0xbd,
	0xdb, 0x0d, 0xa9, 0x5c, 0xf8, 0x75, 0x6c, 0x6e, 0xf7, 0xfd, 0x7b, 0x52, 0xcd, 0xcd, 0xcb, 0xfd,
	0x33, 0x6f, 0x95, 0xc8, 0xf8, 0x25, 0xed, 0x06, 0xae, 0x03, 0x50, 0xc4, 0xe5, 0x3a, 0x1c, 0x92,
	0x00, 0xed, 0x61, 0x04, 0xad, 0x12, 0x53, 0xf2, 0x91, 0xd8, 0x31, 0x92, 0x36, 0x8c, 0x6d, 0x05,
	0x36, 0xf1, 0x51, 0x0d, 0x1f, 0x01, 0xae, 0x98, 0x30, 0x70, 0x3d, 0x3a, 0xb0, 0x62, 0x2f, 0x0c,
	0x90, 0x8c, 0x9f, 0xc1, 0x41, 0xc9, 0xbb, 0x23, 0xdf, 0xf5, 0x7c, 0x7f, 0x40, 0x82, 0x18, 0x29,
	0x18, 0x43, 0x47, 0xc8, 0x07, 0x43, 0x9f, 0xc4, 0x3c, 0xa5, 0x08, 0x5a, 0x8e, 0x17, 0x0d, 0x47,
	0x31, 0x29, 0x1b, 0xd7, 0xb9, 0x4a, 0x30, 0xa3, 0xa1, 0x63, 0xc5, 0x04, 0x35, 0xf0, 0x01, 0xb4,
	0x05, 0x67, 0xfb, 0x61, 0x44, 0x50, 0x93, 0x27, 0x80, 0x12, 0x77, 0x14, 0x38, 0x48, 0xe5, 0x97,
	0x0c, 0xad, 0x4b, 0xde, 0xe5, 0x3a, 0xe2, 0xad, 0x80, 0x4f, 0x20, 0x18, 0xd7, 0x0b, 0x2c, 0xdf,
	0xbb, 0x22, 0x0e, 0xd2, 0x8c, 0x73, 0x50, 0x0b, 0x37, 0xfd, 0xdb, 0x2c, 0xc7, 0xa7, 0xd0, 0xac,
	0xcc, 0x28, 0x13, 0xa2, 0xf5, 0xdb, 0x3b, 0x5e, 0xd3, 0x75, 0xf9, 0xbd, 0x72, 0x55, 0x5b, 0x8c,
	0xc7, 0xf5, 0xc2, 0xc9, 0xd7, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x43, 0x33, 0x33, 0xaa, 0xa4,
	0x04, 0x00, 0x00,
}
